# -*- coding: utf-8 -*-
from data_part1 import DATA

DATA["girls_0_12"] = [
("Lippan mud-art mirror craft kit","Art & Making","A","A rooted Indian art form that ends in a wall-worthy piece."),
("DIY tie-dye fashion kit","Art & Making","B","Make wearable art; every result is one-of-a-kind."),
("Candle-making starter kit","Art & Making","B","Melt, scent and mould; a calming, giftable-back hobby."),
("Soap-making DIY set","Art & Making","B","Chemistry plus beauty; they gift the results proudly."),
("Diamond-dotz sparkle art kit","Art & Making","A","Meditative, satisfying and ends in a framed sparkler."),
("Paper-quilling decor kit","Art & Making","A","Delicate coils become greeting cards and wall art."),
("Embroidery hoop beginner kit","Art & Making","B","A slow, screen-free skill with heirloom potential."),
("Mandala dot-painting coasters","Art & Making","A","Six blank coasters become a usable, gift-worthy set."),
("Fabric marker & tote-bag design kit","Art & Making","A","Design your own bag; wear the art to school."),
("Air-dry clay jewellery-making kit","Art & Making","B","Sculpt, bake-free, then wear their own creations."),
("Bead loom bracelet-making studio","Jewellery Craft","B","Loom-woven bands; a real craft, not just threading."),
("Resin keychain & pendant kit","Jewellery Craft","B","Embed flowers and glitter; magical, giftable results."),
("DIY scrunchie sewing kit","Jewellery Craft","A","Make a drawer full of hair accessories in an afternoon."),
("Charm bracelet build-your-own set","Jewellery Craft","B","A story on the wrist; add charms for milestones."),
("Nail-art (kid-safe peel-off) studio","Jewellery Craft","B","Salon fun at home with washable, gentle polishes."),
("Press-on gem body-art kit","Jewellery Craft","A","Festival sparkle for dress-up days and parties."),
("Friendship-band braiding disc","Jewellery Craft","A","The classic that makes and cements friendships."),
("Clay-bead phone-charm kit","Jewellery Craft","A","On-trend beaded charms they'll actually use."),
("Personalised name-bracelet letter kit","Jewellery Craft","A","Spell any name; part learning, part fashion."),
("Melt-and-pour lip-balm kit","Jewellery Craft","B","Safe, natural balms in flavours they choose."),
("Perfume-making chemistry lab","STEM & Discovery","B","Blends fragrance science with creativity; deeply engaging."),
("Bath-bomb making kit","STEM & Discovery","B","Fizzy chemistry that ends in a spa night."),
("Grow-your-own crystal jewellery","STEM & Discovery","B","Science project you can wear when it's done."),
("Coding robot with storytelling mode","STEM & Discovery","C","Learns logic through characters and quests."),
("Botany pressed-flower science kit","STEM & Discovery","A","Preserve blooms and learn plant parts together."),
("Kitchen-science experiment box","STEM & Discovery","B","Edible, safe experiments that demystify food."),
("Build-a-fountain hydraulics kit","STEM & Discovery","B","Pretty and educational; water physics made lovely."),
("Solar-powered dollhouse light kit","STEM & Discovery","C","Wire real lights into pretend play; sneaky engineering."),
("Weather & rainbow science kit","STEM & Discovery","A","Make rainbows and clouds; wonder plus explanation."),
("DIY kaleidoscope build kit","STEM & Discovery","A","Optics you assemble, then can't stop looking through."),
("Wooden play-kitchen accessories set","Imaginative Play","C","Sturdy props for years of open-ended role-play."),
("Doctor / vet role-play kit","Imaginative Play","B","Empathy and vocabulary through caring play."),
("Magnetic dress-up wooden doll","Imaginative Play","B","Endless outfits; storytelling without tiny lost parts."),
("DIY dollhouse build-and-decorate kit","Imaginative Play","C","Build it, then live stories inside it."),
("Puppet theatre with hand puppets","Imaginative Play","C","A stage for shy kids to find their voice."),
("Tea-party ceramic play set","Imaginative Play","B","Hosting, sharing and manners, disguised as fun."),
("Little-chef baking apron & tools","Imaginative Play","B","Real cooking confidence in kid-sized gear."),
("Pretend market / grocery play set","Imaginative Play","B","Counting, trading and role-play in one basket."),
("Fairy-garden building kit","Imaginative Play","B","A tiny magical world they design and tend."),
("Design-your-own board game kit","Imaginative Play","B","They invent the rules; creativity meets game night."),
("Beginner ukulele with lesson book","Music & Performance","C","Small hands, big joy; a real first instrument."),
("Karaoke mic with Bluetooth speaker","Music & Performance","B","Stage-lit confidence for the household performer."),
("Kids' electronic keyboard with lights","Music & Performance","C","Light-up keys teach songs without a tutor."),
("DIY musical-instrument craft kit","Music & Performance","B","Build shakers and drums, then form a band."),
("Kalimba thumb piano","Music & Performance","B","Instantly playable, soothing and genuinely musical."),
("Ballet / dance starter kit","Music & Performance","B","Encourages movement and grace with real gear."),
("Handbell / chime set with songbook","Music & Performance","B","Colour-coded music-making for pre-readers."),
("Recording microphone toy studio","Music & Performance","C","Records, plays back and delights budding singers."),
("Dress-up performance costume trunk","Music & Performance","C","A whole wardrobe for imaginative role-play."),
("Rhythm & maracas percussion pack","Music & Performance","A","Keeps the beat and the giggles going."),
("Girls' beginner skateboard / cruiser","Outdoor & Active","C","A confidence-building first board in fun colours."),
("Hula-hoop fitness set (weighted)","Outdoor & Active","A","Active play that quietly builds coordination."),
("Garden gymnastics balance beam","Outdoor & Active","C","Backyard practice for the aspiring gymnast."),
("Butterfly / bug explorer backpack","Outdoor & Active","B","Nature kit that gets kids off screens and outside."),
("Kids' cycling helmet & gear set","Outdoor & Active","B","Safety gear that makes riding feel official."),
("Roller skates (adjustable size)","Outdoor & Active","C","Grows with the foot; a season of outdoor fun."),
("Jump-rope with counter","Outdoor & Active","A","Tracks skips; turns exercise into a personal game."),
("Garden trampoline (mini)","Outdoor & Active","D","Endless bouncing energy release for the whole street."),
("Sidewalk-chalk mega art set","Outdoor & Active","A","Turns the driveway into a canvas; social and active."),
("Kite + wind-spinner combo","Outdoor & Active","A","Colourful outdoor play that reads the wind."),
("Personalised adventure storybook","Books & Story","B","She's the heroine; a book she'll ask for nightly."),
("Illustrated women-in-history book","Books & Story","B","Role models and courage in beautiful pages."),
("Interactive pop-up fairy-tale book","Books & Story","A","Paper magic that makes reading an event."),
("Screen-free audio story player","Books & Story","D","Independent, imagination-first listening for ages 3+."),
("Diary with lock & sticker set","Books & Story","A","A private space for first words and secrets."),
("Story-cube imagination dice","Books & Story","A","Roll and invent; storytelling with zero prep."),
("Mythology-for-kids illustrated set","Books & Story","B","Indian and world tales that build cultural roots."),
("Graphic-novel starter series","Books & Story","C","Hooks reluctant readers with art and cliff-hangers."),
("Make-your-own picture-book kit","Books & Story","A","Blank pages and prompts for tiny authors."),
("Book-of-the-month subscription (3m)","Books & Story","C","Anticipation and reading habit, delivered monthly."),
("Star / galaxy ceiling projector","Room & Decor","B","A calming, dreamy bedtime sky she controls."),
("Personalised name LED neon sign","Room & Decor","C","A grown-up room upgrade she'll keep for years."),
("Fairy-light photo-clip curtain","Room & Decor","A","Displays her memories in a warm glow."),
("Cloud / moon soft night lamp","Room & Decor","B","Cute, calming and genuinely useful at bedtime."),
("Personalised height-chart wall decal","Room & Decor","B","A keepsake that literally grows with her."),
("DIY terrarium desk garden","Room & Decor","B","A living, low-maintenance corner of green."),
("Corkboard + polaroid memory set","Room & Decor","B","Her friendships and trips, curated on the wall."),
("Scented shape-cut candle set","Room & Decor","A","Pretty, calming décor that also smells lovely."),
("Personalised door-name plaque","Room & Decor","A","Marks her space as truly her own."),
("Rainbow projector mood light","Room & Decor","B","Colour-shifting ambience for reading and winding down."),
("Kids' mindfulness & feelings card deck","Wellness","A","Names big emotions; a gentle tool for tough days."),
("Yoga-for-kids mat & pose cards","Wellness","B","Movement and calm in a playful, guided format."),
("Gratitude journal for children","Wellness","A","Builds a lifelong habit of noticing the good."),
("Kinetic sand sensory tray","Wellness","B","Deeply calming tactile play for anxious moments."),
("DIY stress-ball / squishy kit","Wellness","A","Make their own fidget; comfort they crafted."),
("Weighted plush comfort toy","Wellness","C","Gentle pressure that soothes at bedtime."),
("Aromatherapy dough / play kit","Wellness","B","Scented, squishy calm for over-stimulated days."),
("Affirmation card set for kids","Wellness","A","Daily confidence in bite-sized, kind reminders."),
("Bedtime meditation audio + book","Wellness","B","Winds down racing minds without a screen."),
("Emotion-faces wooden puzzle","Wellness","A","Playful emotional literacy for the youngest."),
("Design-your-own fashion sketch kit","Dress-Up & Fashion","B","Stencils and pens for the budding designer."),
("Dress-up costume + accessories trunk","Dress-Up & Fashion","C","A whole wardrobe for imaginative role-play."),
("DIY hair-accessory making kit","Dress-Up & Fashion","B","Clips, bows and bands she makes and wears."),
("Fashion-design magnetic dress-up board","Dress-Up & Fashion","B","Mix-and-match outfits with no lost pieces."),
("Kids' vanity + play-makeup (washable)","Dress-Up & Fashion","C","Safe, washable glam for dress-up days."),
("Sewing-for-kids beginner kit","Dress-Up & Fashion","B","A real, gentle first craft with wearable results."),
("Personalised cape / superhero costume","Dress-Up & Fashion","B","Her name on a hero's cape; pure imagination fuel."),
("Design-your-own T-shirt fabric kit","Dress-Up & Fashion","A","Wearable art she designs and shows off at school."),
("Princess / fairy dress-up set","Dress-Up & Fashion","C","Classic imaginative play that never gets old."),
("Kids' fashion runway sticker book","Dress-Up & Fashion","A","Style stories she creates page after page."),
]
