# -*- coding: utf-8 -*-
from data_part1 import DATA

DATA["unisex"] = [
("Personalised couple star-map frame","Couples","B","The night sky of the day they met; deeply romantic."),
("Custom couple caricature on wood","Couples","B","A playful, personal keepsake of the two of them."),
("Matching engraved couple bracelets","Couples","B","Subtle, wearable symbols of a shared bond."),
("Long-distance touch-lamp pair","Couples","D","Tap one, the other glows; connection across cities."),
("Couple's cooking / date-night kit","Couples","C","A shared experience-in-a-box for a memorable evening."),
("Personalised photo-cube / rolling cube","Couples","C","Rotating photos of their story; a novel keepsake."),
("'Our adventures' scratch-off map","Couples","B","Scratch the places they've been together; goal-setting fun."),
("Custom song-lyric / Spotify frame","Couples","B","Their anthem, framed; personal and heartfelt."),
("Couple's spa / massage voucher","Couples","D","Shared relaxation; a memory over an object."),
("Message-in-a-bottle keepsake set","Couples","A","Little notes to open on hard or special days."),
("'Open when...' letter box set","Friends","B","Notes for every mood; thoughtful and unforgettable."),
("Personalised friendship-journey frame","Friends","B","Milestones of a friendship, mapped and framed."),
("Matching best-friend keychains","Friends","A","A small, everyday symbol of the bond."),
("Custom bobblehead of your friend","Friends","C","A hilarious, personal desk companion."),
("Shared-memory photo-book (curated)","Friends","C","Years of inside jokes in one keepsake."),
("Friendship-day caricature","Friends","B","Captures the duo's personality with humour."),
("Board-game / party-game night set","Friends","B","Fuels the get-togethers that keep friends close."),
("Personalised playlist / cassette keychain","Friends","A","Their shared soundtrack in a retro trinket."),
("Group-trip experience voucher","Friends","C","An adventure to share; the ultimate friend gift."),
("Customised inside-joke mug / tee","Friends","A","A daily-use item that makes them grin."),
("Personalised sibling photo-frame","Siblings & Family","B","A warm keepsake of the sibling bond."),
("Custom family-portrait illustration","Siblings & Family","B","The whole family as art; treasured on the wall."),
("Rakhi / festival personalised hamper","Siblings & Family","C","Thoughtful, occasion-perfect and full of meaning."),
("Sibling caricature standee","Siblings & Family","B","Playful, personal and instantly loved."),
("'Reasons I love you' message jar","Siblings & Family","A","Little notes that land straight in the heart."),
("Family-recipe keepsake cookbook","Siblings & Family","C","Preserves the flavours of home for generations."),
("Personalised family-tree wall art","Siblings & Family","C","Roots and generations honoured beautifully."),
("Matching family sweatshirts / co-ord","Siblings & Family","C","Photo-ready togetherness for the whole clan."),
("Custom voice-note keepsake frame","Siblings & Family","B","Plays a loved one's message on demand."),
("Family board-game night bundle","Siblings & Family","B","Screen-free evenings that bring everyone together."),
("Personalised desk-nameplate / organiser","Coworkers","B","A dignified, useful upgrade for their workspace."),
("Custom profession caricature","Coworkers","B","A witty nod to their role; a desk favourite."),
("Premium coffee / tea desk hamper","Coworkers","C","Fuels the workday with a touch of indulgence."),
("Desk plant + minimalist planter","Coworkers","B","A bit of calm and life for the office corner."),
("Personalised notebook + pen set","Coworkers","B","Thoughtful, professional and genuinely used."),
("Farewell / promotion memory frame","Coworkers","B","Marks a milestone with warmth and class."),
("Wireless charging desk-clock","Coworkers","C","A clean, useful gadget for any professional."),
("Motivational desk-mat (personalised)","Coworkers","B","Their name and goals under the keyboard daily."),
("Trophy / recognition award (custom)","Coworkers","B","Celebrates a win in a keepsake they'll display."),
("Team-experience / lunch voucher","Coworkers","C","Shared time that strengthens work bonds."),
("Personalised family-name nameplate","Housewarming","B","Marks the new home with pride from day one."),
("Custom house-portrait illustration","Housewarming","C","Their new home as art; a heartfelt first-day gift."),
("Premium scented-candle gift set","Housewarming","B","A warm, welcoming scent for the new space."),
("Indoor plant + designer planter","Housewarming","B","A living housewarming that grows with the home."),
("Personalised doormat","Housewarming","B","A cheerful, custom welcome at the front door."),
("Bar / entertaining accessory set","Housewarming","C","Ready-to-host essentials for the new place."),
("Wall-clock / statement décor piece","Housewarming","C","A finishing touch for the fresh living room."),
("Custom map / coordinates art of the home","Housewarming","B","Their address turned into meaningful wall art."),
("Kitchen-essentials starter hamper","Housewarming","C","Practical, thoughtful and immediately useful."),
("Personalised key-holder / entry organiser","Housewarming","B","Tidy, warm and useful from the very first day."),
("Levitating / floating moon lamp","Quirky & Fun","D","A gravity-defying centrepiece and conversation-starter."),
("Anti-gravity water-drop humidifier","Quirky & Fun","B","Mesmerising floating droplets; oddly delightful."),
("Self-stirring / temperature mug","Quirky & Fun","B","A small, futuristic daily luxury."),
("Retro voice-recorder tape keychain","Quirky & Fun","A","Records and replays; charmingly nostalgic."),
("Levitating Bluetooth speaker","Quirky & Fun","D","Floating 360-degree sound; instant wow."),
("Reverse / capsule quirky umbrella","Quirky & Fun","B","A practical gift with a genuine style twist."),
("Mini arcade retro-game console","Quirky & Fun","B","Pocket nostalgia loaded with childhood classics."),
("Galaxy / aurora projector lamp","Quirky & Fun","B","Turns any room into a dreamy light show."),
("Funny personalised prank gift box","Quirky & Fun","C","A shared laugh wrapped as a gift."),
("Magnetic sand / kinetic desk toy","Quirky & Fun","B","Hypnotic, calming fidget décor for any desk."),
("Bonsai plant + care kit","Plants & Green","C","A living, meditative hobby for any windowsill."),
("Self-watering smart planter","Plants & Green","C","Keeps greenery thriving even for the forgetful."),
("Terrarium DIY kit","Plants & Green","B","A tiny green world they build and tend."),
("Lucky bamboo / money-plant arrangement","Plants & Green","B","A thoughtful, low-maintenance good-luck gift."),
("Herb-garden windowsill kit","Plants & Green","B","Fresh herbs on hand for the home cook."),
("Air-purifying plant duo + pots","Plants & Green","B","Cleaner air and calm in one living gift."),
("Personalised engraved planter","Plants & Green","B","A custom pot that makes any plant a keepsake."),
("Succulent-collection starter set","Plants & Green","B","Hardy, charming greenery for beginners."),
("Grow-your-own flowers kit","Plants & Green","A","Seeds to blooms; a rewarding little project."),
("Smart plant-care sensor","Plants & Green","C","Tells them exactly what the plant needs; clever."),
("Curated monthly subscription box (3m)","Subscriptions","D","Anticipation and delight delivered every month."),
("Streaming / OTT annual gift card","Subscriptions","C","Endless entertainment; safe and always welcome."),
("Coffee / tea subscription (3 months)","Subscriptions","C","A fresh discovery for the ritual-lover monthly."),
("Book-of-the-month subscription","Subscriptions","C","A new read and a habit, delivered."),
("Audiobook / podcast annual subscription","Subscriptions","C","Stories for commutes, chores and downtime."),
("Meal-kit / gourmet-snack box","Subscriptions","C","Cooking adventures without the grocery run."),
("Experience-day gift voucher (choose-your-own)","Subscriptions","D","They pick the adventure; the flexible perfect gift."),
("Fitness / meditation app annual gift","Subscriptions","B","A year of wellbeing that keeps giving."),
("Plant / gardening subscription","Subscriptions","C","Fresh greenery delivered for the plant-lover."),
("Personalised digital-magazine subscription","Subscriptions","C","Their passion, delivered regularly and thoughtfully."),
("Custom illustrated portrait (from photo)","Sentimental","B","A loved one or pet as art; treasured and unique."),
("Personalised message / memory jar (365)","Sentimental","A","A year of little notes to open one by one."),
("Spotify-code + photo keepsake","Sentimental","A","A song and a memory in one small treasure."),
("Personalised wooden photo puzzle","Sentimental","A","A shared memory to build together and keep."),
("Custom map of 'where it all began'","Sentimental","B","A meaningful place framed with a date."),
("Engraved keepsake box","Sentimental","B","A beautiful home for letters, trinkets and memories."),
("Personalised year-in-review photo book","Sentimental","C","A whole year of memories, curated and bound."),
("Fingerprint / handprint keepsake art","Sentimental","B","A literal touch of a loved one, framed."),
("Voice-waveform art (their words)","Sentimental","B","A loved one's words turned into wall art."),
("Time-capsule letter kit","Sentimental","A","Notes to a future self or loved one; profoundly personal."),
("Personalised anniversary star-map","Anniversary & Milestone","B","The sky of the day it all began, framed."),
("Custom '10/25/50 years' keepsake","Anniversary & Milestone","C","Marks a milestone with warmth and class."),
("Engraved milestone crystal / plaque","Anniversary & Milestone","C","A striking keepsake for a landmark moment."),
("Year-in-review photo-book (curated)","Anniversary & Milestone","C","A whole chapter of memories, beautifully bound."),
("Personalised couple / family portrait","Anniversary & Milestone","B","Their people as art; treasured for years."),
("Custom song / voice-note keepsake frame","Anniversary & Milestone","B","Plays a loved one's message on demand."),
("Milestone experience gift box","Anniversary & Milestone","D","A curated celebration ready to redeem."),
("Time-capsule / letters keepsake kit","Anniversary & Milestone","A","Notes to open on future milestones; deeply personal."),
("Personalised wedding / event caricature","Anniversary & Milestone","B","A playful, personal memory of the big day."),
("Coordinates art of a milestone place","Anniversary & Milestone","B","A meaningful place framed with a date."),
]

DATA["premium"] = [
("Flagship noise-cancelling headphones","Luxury Tech","D","Best-in-class silence and sound; a daily-used indulgence."),
("Premium smartwatch (top-tier)","Luxury Tech","D","Health, style and connection in one statement piece."),
("High-end espresso / bean-to-cup machine","Luxury Tech","D","Cafe-quality mornings; a passion gift used every day."),
("Robot vacuum + mop (self-emptying)","Luxury Tech","D","Buys back weekend hours; universally loved."),
("Premium projector for home cinema","Luxury Tech","D","Turns any wall into a movie night to remember."),
("Flagship wireless earbuds (ANC)","Luxury Tech","D","Effortless premium audio for work and travel."),
("Smart-home flagship speaker / display","Luxury Tech","D","The elegant brain of a connected home."),
("Drone with pro 4K camera","Luxury Tech","D","Aerial creativity and flying joy; a big statement."),
("High-refresh gaming monitor / setup piece","Luxury Tech","D","A serious upgrade the gamer will never forget."),
("Premium e-reader (top model)","Luxury Tech","D","A luxurious library for the devoted reader."),
("Luxury multi-night staycation (for two)","Premium Experiences","D","A curated escape at a five-star property."),
("Hot-air-balloon ride for two","Premium Experiences","D","A once-in-a-lifetime shared memory."),
("Supercar / superbike track experience","Premium Experiences","D","A bucket-list adrenaline day, retold for years."),
("Private yacht / houseboat day","Premium Experiences","D","An indulgent, unforgettable day on the water."),
("Fine-dining chef's-table for two","Premium Experiences","D","An evening of culinary theatre and craft."),
("Luxury wellness / spa retreat","Premium Experiences","D","Deep rejuvenation guided by expert hands."),
("Wildlife-safari luxury package","Premium Experiences","D","Nature at its most thrilling, in comfort."),
("Heritage-palace stay experience","Premium Experiences","D","Royal living for a night; a story to keep."),
("Private wine / whisky tasting session","Premium Experiences","D","A guided, indulgent evening for the connoisseur."),
("Scenic-helicopter / flying experience","Premium Experiences","D","The world from above; pure, memorable awe."),
("Designer statement floor lamp","High-End Home","D","A sculptural centrepiece that defines a room."),
("Premium bed-linen / bedding set","High-End Home","D","Hotel-luxury sleep felt every single night."),
("Luxury aroma-diffuser + fragrance set","High-End Home","D","A signature home scent with designer presence."),
("Handcrafted décor / art object","High-End Home","D","A one-of-a-kind piece with real character."),
("Premium coffee-table book collection","High-End Home","D","Curated, beautiful volumes that anchor a room."),
("Massage chair (full-body recliner)","High-End Home","D","A home-spa throne for daily luxury."),
("Designer dinnerware / serveware set","High-End Home","D","Hosting elegance for the entertaining household."),
("Smart-lighting whole-room system","High-End Home","D","App-controlled ambience that transforms the space."),
("Premium indoor-plant + designer planter","High-End Home","D","A living statement for the design-led home."),
("Custom neon / light-art installation","High-End Home","D","Personalised light as a bold décor centrepiece."),
("Automatic mechanical watch (heirloom)","Jewellery & Watches","D","A milestone timepiece to keep and pass on."),
("Diamond / precious-stone jewellery","Jewellery & Watches","D","Timeless brilliance for a landmark occasion."),
("Gold personalised name / initial piece","Jewellery & Watches","D","A luxurious, personal keepsake worn with pride."),
("Pearl luxury jewellery set","Jewellery & Watches","D","Classic elegance for the most special moments."),
("Designer sunglasses (premium)","Jewellery & Watches","D","A face-defining accessory built to last."),
("Solid-gold / platinum band (custom)","Jewellery & Watches","D","A meaningful, enduring symbol crafted to order."),
("Luxury fountain pen (limited edition)","Jewellery & Watches","D","A collectible writing instrument of real prestige."),
("Premium leather goods set (bag/wallet)","Jewellery & Watches","D","Craftsmanship that ages beautifully with them."),
("Engraved milestone crystal award","Jewellery & Watches","D","Marks an achievement in striking, keepsake form."),
("Personalised diamond-accent pendant","Jewellery & Watches","D","Sparkle plus personal meaning; unforgettable."),
("Premium single-malt / spirits gift set","Gourmet Luxury","D","A distinguished bottle for the discerning palate."),
("Luxury chocolate / dessert hamper","Gourmet Luxury","D","An indulgent showpiece of the finest treats."),
("Gourmet gift-hamper (curated, premium)","Gourmet Luxury","D","A lavish spread of the best gourmet finds."),
("Fine-tea / rare-coffee collection","Gourmet Luxury","D","A connoisseur's journey through rare flavours."),
("Premium dry-fruit & saffron hamper","Gourmet Luxury","D","A rich, festive gift of the finest ingredients."),
("Artisanal cheese & charcuterie premium set","Gourmet Luxury","D","Turns an evening into a gourmet celebration."),
("Luxury bar / cocktail-craft set","Gourmet Luxury","D","Everything for a spectacular home-bar showpiece."),
("Champagne / sparkling celebration set","Gourmet Luxury","D","A toast-worthy gift for landmark moments."),
("Premium honey / exotic-condiment collection","Gourmet Luxury","D","Rare, gourmet pantry treasures for the foodie."),
("Chef's premium cookware statement piece","Gourmet Luxury","D","A lifetime kitchen upgrade for the serious cook."),
("Premium luggage set (hard-shell)","Travel Luxury","D","Handsome, durable carry for the frequent flyer."),
("Full-grain leather weekender bag","Travel Luxury","D","Timeless travel gear that ages beautifully."),
("Luxury travel-accessory gift box","Travel Luxury","D","Curated essentials for the seasoned traveller."),
("Premium travel headphones (ANC)","Travel Luxury","D","Peace and premium sound on every journey."),
("Designer passport + travel-wallet set","Travel Luxury","D","Sophisticated organisation for the globetrotter."),
("Curated travel-experience gift card (premium)","Travel Luxury","D","They choose a world-class experience; ultimate flexibility."),
("Luxury camera / travel-photography kit","Travel Luxury","D","For capturing journeys in stunning detail."),
("Premium car-travel gadget bundle","Travel Luxury","D","Upgrades every road trip with smart, sleek tech."),
("First-class lounge / travel-perk membership","Travel Luxury","D","Turns airport waits into indulgent comfort."),
("Personalised luxury travel journal set","Travel Luxury","D","A beautiful home for the stories of their travels."),
("Full-body premium massage chair","Wellness Luxury","D","A home-spa throne for daily deep relaxation."),
("Luxury spa-retreat weekend gift","Wellness Luxury","D","A restorative escape for body and mind."),
("Premium fitness smart-mirror / equipment","Wellness Luxury","D","A high-end home gym that guides every workout."),
("High-end percussion massage device","Wellness Luxury","D","Pro-grade recovery that feels genuinely luxurious."),
("Ayurveda luxury wellness package","Wellness Luxury","D","Deep, traditional rejuvenation by expert hands."),
("Premium sleep-tech bundle","Wellness Luxury","D","Better sleep as the ultimate modern luxury."),
("Luxury skincare ritual collection","Wellness Luxury","D","A considered, indulgent daily self-care upgrade."),
("Infrared sauna blanket","Wellness Luxury","D","At-home detox-and-relax; a wellness statement gift."),
("Premium meditation / breathwork device","Wellness Luxury","D","Stress relief made tangible and beautifully designed."),
("Personalised luxury robe + spa hamper","Wellness Luxury","D","Hotel-grade comfort with a bespoke touch."),
("Collector-grade franchise replica (1:1)","Collectibles","D","A museum-worthy fan piece that owns the room."),
("Limited-edition art print (signed)","Collectibles","D","Gallery-grade wall art with genuine collectible value."),
("Premium vinyl turntable + record set","Collectibles","D","Analog warmth and cover-art romance, elevated."),
("Handcrafted premium chess set","Collectibles","D","A heirloom for the strategist; art and game in one."),
("Luxury model-build (detailed kit)","Collectibles","D","A prestige project and a striking display piece."),
("Signed sports / music memorabilia","Collectibles","D","A piece of their passion, authenticated and treasured."),
("Premium telescope (advanced)","Collectibles","D","Deep-sky wonder for the serious stargazer."),
("Designer statement sculpture","Collectibles","D","A bold, characterful centrepiece for the home."),
("Rare-book / first-edition collectible","Collectibles","D","A treasure for the bibliophile; lasting and meaningful."),
("Custom-built PC / high-end setup piece","Collectibles","D","The dream upgrade for the serious enthusiast."),
("Bespoke portrait painting (commissioned)","Personalised Luxury","D","A loved one immortalised by a real artist."),
("Custom engraved luxury watch","Personalised Luxury","D","A milestone timepiece made unmistakably theirs."),
("Personalised premium leather-goods set","Personalised Luxury","D","Monogrammed craftsmanship for everyday luxury."),
("Custom family-portrait sculpture / art","Personalised Luxury","D","The whole family as a striking keepsake."),
("Engraved fine-jewellery keepsake","Personalised Luxury","D","Precious, personal and worn with love for life."),
("Bespoke fragrance (custom-blended)","Personalised Luxury","D","A signature scent created uniquely for them."),
("Personalised luxury photo-book (premium)","Personalised Luxury","D","A life's memories bound in a beautiful volume."),
("Custom star-map on premium canvas","Personalised Luxury","D","A meaningful night sky, rendered as fine art."),
("Monogrammed premium bar / desk set","Personalised Luxury","D","Executive elegance made personal."),
("Bespoke keepsake box (handcrafted)","Personalised Luxury","D","A beautiful, custom home for a lifetime of treasures."),
("International short-getaway package","Big-Ticket Experiences","D","A dream trip; the most memorable gift of all."),
("Luxury dinner-cruise for two","Big-Ticket Experiences","D","An elegant evening on the water to remember."),
("Private cooking class with a chef","Big-Ticket Experiences","D","A hands-on, gourmet experience they'll treasure."),
("Adventure-sports premium package","Big-Ticket Experiences","D","Skydiving-tier thrills for the bold at heart."),
("Luxury wildlife / jungle-lodge stay","Big-Ticket Experiences","D","Nature and comfort in perfect, memorable balance."),
("Concert / premium-event VIP tickets","Big-Ticket Experiences","D","A front-row memory of a lifetime."),
("Personal-styling / makeover experience","Big-Ticket Experiences","D","A confidence-boosting, feel-amazing day."),
("Photography destination-shoot package","Big-Ticket Experiences","D","Stunning, professional images in a dream location."),
("Golf-resort premium weekend","Big-Ticket Experiences","D","A dream escape for the passionate golfer."),
("Bespoke anniversary celebration package","Big-Ticket Experiences","D","A curated, once-in-a-lifetime milestone experience."),
]
