# -*- coding: utf-8 -*-
from data_part1 import DATA

DATA["teen_boys"] = [
("Handheld retro game console (500+ games)","Tech & Gadgets","B","Nostalgic arcade in the pocket; instant crowd-pleaser."),
("Over-ear gaming headset with mic","Tech & Gadgets","C","Immersion and squad comms; a genuine gaming upgrade."),
("Mechanical keyboard (compact 60%)","Tech & Gadgets","C","The clack that gamers obsess over; a desk statement."),
("RGB gaming mouse with programmable buttons","Tech & Gadgets","B","Precision and glow; the accessory every gamer notices."),
("Portable Bluetooth speaker (rugged)","Tech & Gadgets","C","Loud, drop-proof and travels to every hangout."),
("Smartwatch with fitness & notifications","Tech & Gadgets","D","Grown-up gadget that tracks runs and pings."),
("Levitating / floating Bluetooth speaker","Tech & Gadgets","D","A floating speaker is pure conversation-starter magic."),
("Phone gimbal stabiliser for creators","Tech & Gadgets","C","Smooth cinematic video for the aspiring YouTuber."),
("Wireless earbuds with low-latency mode","Tech & Gadgets","C","Gaming-grade audio without the wires."),
("Smart LED strip lights (app + music sync)","Tech & Gadgets","B","Turns any room into a synced, glowing setup."),
("Arc-reactor / superhero LED desk lamp","Gaming Culture","D","Collector-grade fan piece that owns the desk."),
("Anime / game franchise collectible figure","Gaming Culture","C","Speaks his fandom fluently; display-worthy."),
("Controller charging dock station","Gaming Culture","B","Ends dead-controller frustration in style."),
("Gaming-desk cable & setup organiser kit","Gaming Culture","B","The clean-setup upgrade every gamer craves."),
("Retro tape-recorder voice keychain","Gaming Culture","A","Quirky mini-cassette that records and plays back."),
("Levitating moon / planet lamp","Gaming Culture","D","A floating lamp that defies gravity and expectations."),
("Pixel-art night-light clock","Gaming Culture","B","Retro-game aesthetic meets a useful desk clock."),
("Fandom hoodie / graphic tee (personalised)","Gaming Culture","B","Wearable identity; his interests, his uniform."),
("Enamel-pin collection (game/anime)","Gaming Culture","A","Low-cost, high-meaning; badges of belonging."),
("Custom gamertag neon sign","Gaming Culture","C","His handle in light; the ultimate setup flex."),
("Adjustable dumbbell set","Fitness & Sport","C","Home strength training that scales as he grows."),
("Football / basketball (pro grade)","Fitness & Sport","B","A serious ball for the kid who lives for the game."),
("Resistance-band home workout kit","Fitness & Sport","B","Full-body training that fits in a drawer."),
("Skateboard (complete, quality trucks)","Fitness & Sport","C","A real board is a hobby, a friend group, an identity."),
("Fitness tracker band","Fitness & Sport","B","Gamifies movement; steps become a personal challenge."),
("Boxing gloves + hand-wrap set","Fitness & Sport","C","Discipline, fitness and a serious stress outlet."),
("Insulated gym / sports water bottle","Fitness & Sport","B","Practical, sturdy and quietly cool."),
("Pull-up bar (doorway)","Fitness & Sport","B","No-excuse strength gains in the bedroom doorway."),
("Cricket bat (English willow, junior)","Fitness & Sport","D","For the serious young cricketer; a treasured upgrade."),
("Balance / wobble board trainer","Fitness & Sport","B","Core and coordination for board-sport crossover."),
("USB podcast / studio microphone","Music & Creation","C","Launchpad for podcasts, streams and music."),
("Beginner electric guitar starter pack","Music & Creation","D","The instrument that defines a teenage phase, gloriously."),
("MIDI mini keyboard for music production","Music & Creation","C","Bedroom-producer starter for the beat-maker."),
("Lo-fi beat-making pad controller","Music & Creation","C","Finger-drumming fun that becomes real production."),
("Vinyl record player (portable)","Music & Creation","D","Analog cool for the teen with taste."),
("Guitar effects pedal (multi-fx)","Music & Creation","C","Unlocks a hundred tones for the guitarist."),
("Ring light + phone tripod creator kit","Music & Creation","B","Studio lighting for content, calls and covers."),
("DJ controller (beginner)","Music & Creation","D","Mix tracks at parties; a genuinely social hobby."),
("Acoustic guitar (quality beginner)","Music & Creation","C","Timeless, portable and endlessly re-giftable joy."),
("Kalimba / handpan (portable)","Music & Creation","B","Soothing, instantly playable and impressively different."),
("Aesthetic desk-setup starter bundle","Desk & Study","C","Mat, stand and organiser; an instant glow-up."),
("Laptop stand + wireless keyboard combo","Desk & Study","C","Ergonomic upgrade for study and gaming alike."),
("Monitor light bar (eye-care)","Desk & Study","C","Reduces late-night eye strain; premium desk vibe."),
("Noise-cancelling study headphones","Desk & Study","D","Focus armour for exam season and open homes."),
("Personalised motivational desk mat","Desk & Study","B","His name, his goals, under his keyboard daily."),
("Smart study lamp with timer","Desk & Study","C","Pomodoro-friendly lighting for focused sessions."),
("Cable-management & charging valet","Desk & Study","B","Tidy tech; the small upgrade that feels premium."),
("Digital drawing tablet (entry)","Desk & Study","D","For the doodler ready to go digital."),
("Whiteboard + habit-tracker desk set","Desk & Study","B","Turns goals visible; quietly powerful for teens."),
("Blue-light glasses (stylish)","Desk & Study","B","Screen comfort with a look he'll actually wear."),
("Minimalist leather-strap watch","Style & Accessories","C","A first grown-up watch; understated and lasting."),
("Personalised leather wallet","Style & Accessories","B","Engraved everyday carry that says he matters."),
("Streetwear crossbody sling bag","Style & Accessories","B","On-trend, practical and effortlessly cool."),
("Sunglasses (polarised, trend cut)","Style & Accessories","B","Instant confidence; a look he'll live in."),
("Beanie + graphic-sock gift bundle","Style & Accessories","A","Low-stakes fun style pieces teens genuinely wear."),
("Personalised dog-tag / chain","Style & Accessories","B","Subtle identity jewellery with his name or date."),
("Cap collection (snapback set)","Style & Accessories","B","Everyday headwear; safe, on-point, appreciated."),
("Perfume / body-spray gift set","Style & Accessories","B","The teenage grooming upgrade they secretly want."),
("Canvas high-top sneakers","Style & Accessories","C","A wardrobe staple with real personality."),
("Weekender duffel for trips","Style & Accessories","C","Grown-up travel gear for the independence years."),
("Beginner DSLR / mirrorless (used-grade)","Hobbies & Making","D","For the teen serious about photography as an art."),
("Astronomy telescope (intermediate)","Hobbies & Making","D","Rings of Saturn from the terrace; awe on tap."),
("Model-building kit (car/aircraft/Gundam)","Hobbies & Making","C","Patience, focus and a display piece at the end."),
("Skateboard / longboard tool & wheel kit","Hobbies & Making","B","For the boarder who tinkers with his ride."),
("Drone (beginner, camera)","Hobbies & Making","D","Aerial video and pure flying fun; huge wow factor."),
("Leathercraft starter kit","Hobbies & Making","C","Make a real wallet; a rare, tactile modern skill."),
("Chess set + strategy book bundle","Hobbies & Making","B","Fuels a competitive mind; timeless and portable."),
("Rubik's-cube speedsolving pro set","Hobbies & Making","B","A genuine skill and party trick in one."),
("3D-printing pen (advanced)","Hobbies & Making","C","Draws objects in mid-air; endless making."),
("Calligraphy / brush-lettering kit","Hobbies & Making","B","A calming, screen-free creative outlet with real payoff."),
("EDC multitool card (wallet-sized)","Everyday Utility","A","Twelve tools in a card; feels like a superpower."),
("Windproof rechargeable arc lighter","Everyday Utility","A","Flameless, USB-charged and genuinely handy-cool."),
("Compact power bank (fast charge)","Everyday Utility","B","Never-dead phone; the gift that quietly saves days."),
("Magnetic phone-mount + charger","Everyday Utility","B","Desk and travel convenience in one clean gadget."),
("Mini portable vacuum for desk/car","Everyday Utility","A","Oddly satisfying and actually useful for setups."),
("Keychain LED torch multitool","Everyday Utility","A","Pocket utility with a bottle-opener grin."),
("Digital luggage / gym-bag scale","Everyday Utility","A","Small, clever and appreciated for years."),
("Sneaker-cleaning care kit","Everyday Utility","B","Keeps his prized kicks fresh; thoughtful and specific."),
("Insulated flask that keeps ice 24h","Everyday Utility","B","Practical flex for school, gym and treks."),
("Fidget mechanical-switch keychain","Everyday Utility","A","Satisfying clicky stress-relief he'll carry everywhere."),
("Beginner coding / robotics kit (teen)","Skills & Side-Hustle","C","Turns screen time into a real, future-proof skill."),
("Content-creator lighting + mic bundle","Skills & Side-Hustle","C","Everything to start a channel or podcast well."),
("Stock-market / finance board game","Skills & Side-Hustle","B","Teaches money smarts through genuinely fun play."),
("Beginner sneaker / thrift-flip kit","Skills & Side-Hustle","B","Feeds the reselling side-hustle bug creatively."),
("DIY electronics invention kit","Skills & Side-Hustle","C","Build real gadgets; a maker's launchpad."),
("Photography 'learn manual mode' course kit","Skills & Side-Hustle","C","Levels up a hobby into a genuine skill."),
("Public-speaking / debate skills book set","Skills & Side-Hustle","A","Confidence tools for the ambitious teen."),
("3D-printing pen + project book","Skills & Side-Hustle","C","Designs objects in mid-air; endless making."),
("Chess-improvement course + set","Skills & Side-Hustle","B","Sharpens strategy for the competitive mind."),
("Digital-art tablet starter","Skills & Side-Hustle","D","For the doodler ready to go pro-digital."),
("Beginner slackline kit","Adventure & Outdoors","B","Balance, focus and outdoor fun in one line."),
("Camping starter kit (tent + gear)","Adventure & Outdoors","D","Fuels weekend adventures and independence."),
("Skateboard / longboard (quality)","Adventure & Outdoors","C","A board is a hobby, a crew and an identity."),
("Mountain-bike accessories bundle","Adventure & Outdoors","C","Lights, tools and gear for the trail-rider."),
("Trekking daypack + hydration bladder","Adventure & Outdoors","C","Ready-to-go gear for the hills-loving teen."),
("Action camera (rugged, waterproof)","Adventure & Outdoors","D","Captures every jump, ride and dive in HD."),
("Bouldering / climbing-gym pass","Adventure & Outdoors","C","A social, strength-building adventure hobby."),
("Fishing starter rod-and-tackle kit","Adventure & Outdoors","C","A calm, patient outdoor pastime."),
("Portable inflatable kayak / SUP","Adventure & Outdoors","D","Water adventures without a boat or storage."),
("Survival / EDC outdoor multitool kit","Adventure & Outdoors","B","Feels like a superpower on every camping trip."),
]

DATA["teen_girls"] = [
("Personalised name LED neon sign","Aesthetic & Room","C","The Pinterest-room centrepiece she's been eyeing."),
("Galaxy / sunset projector lamp","Aesthetic & Room","B","Transforms the room's mood in one click."),
("Fairy-light photo-clip curtain","Aesthetic & Room","A","Turns her memories into glowing wall art."),
("Instant / mini photo printer","Aesthetic & Room","D","Prints phone pics on the spot; deeply loved by teens."),
("Corkboard + polaroid memory kit","Aesthetic & Room","B","A curated wall of friendships and trips."),
("Aesthetic desk-organiser bundle","Aesthetic & Room","B","Pretty, functional and endlessly rearranged."),
("Cloud / moon ambient night lamp","Aesthetic & Room","B","Soft, dreamy light for reading and winding down."),
("Custom Spotify-code framed poster","Aesthetic & Room","B","Her favourite song, scannable, on the wall."),
("Boho macramé wall hanging","Aesthetic & Room","B","On-trend texture that levels up any corner."),
("Rainbow / disco projector mood light","Aesthetic & Room","B","Party-in-a-room lighting for get-togethers."),
("At-home spa gift hamper","Self-Care & Beauty","C","A full pamper night in a beautiful box."),
("Skincare starter fridge (mini)","Self-Care & Beauty","D","Chills her serums; a viral, coveted upgrade."),
("Personalised jade-roller & gua-sha set","Self-Care & Beauty","B","Ritual self-care with a gift-worthy finish."),
("DIY natural cosmetics-making kit","Self-Care & Beauty","B","Make lip balm and scrubs; creative and useful."),
("Bath-bomb & candle self-care box","Self-Care & Beauty","B","Instant unwind ritual after a long school week."),
("Silk pillowcase + scrunchie set","Self-Care & Beauty","B","Gentle-on-hair luxury she'll notice nightly."),
("Hair-styling tools starter kit","Self-Care & Beauty","C","Salon looks at home; genuinely used daily."),
("Perfume-discovery sampler set","Self-Care & Beauty","B","Finds her signature scent without a big spend."),
("Aromatherapy diffuser + oils","Self-Care & Beauty","B","Calming ambience and self-care in one."),
("Personalised makeup / vanity bag","Self-Care & Beauty","B","Organised beauty with her name on it."),
("Digital drawing tablet (entry)","Creative & Art","D","For the doodler ready to make digital art seriously."),
("Watercolour + brush-pen art set","Creative & Art","B","A calming, expressive hobby with lovely results."),
("Diamond-painting art kit","Creative & Art","A","Meditative sparkle-art that ends framed on the wall."),
("Embroidery / punch-needle starter kit","Creative & Art","B","A slow, satisfying craft with heirloom charm."),
("Hand-lettering & calligraphy kit","Creative & Art","B","Turns notes and cards into art; genuinely useful."),
("DIY candle-making studio","Creative & Art","B","Scented, giftable results; a whole aesthetic hobby."),
("Resin art & coaster-making kit","Creative & Art","B","Glossy, giftable pieces; creative and on-trend."),
("Pottery / clay air-dry kit","Creative & Art","B","Handmade trinket dishes and mugs; therapeutic."),
("Sketchbook + pro pencil set","Creative & Art","B","Quality tools that take a hobby seriously."),
("Sticker-making & journaling kit","Creative & Art","A","Fuels the journaling and scrapbooking obsession."),
("Personalised leather journal + pen","Journaling","B","A private, beautiful space with her name embossed."),
("Aesthetic bullet-journal starter set","Journaling","B","Washi, stencils and pens; the full BuJo kit."),
("Guided self-discovery / manifestation journal","Journaling","B","Structured prompts for goals, gratitude and growth."),
("Custom 12-month photo planner","Journaling","B","Her memories built into her daily planning."),
("Vision-board DIY kit","Journaling","B","Turns dreams visible; a genuine mindset tool."),
("Wax-seal & letter-writing set","Journaling","B","Old-world romance for the sentimental writer."),
("Sticker + washi-tape mega bundle","Journaling","A","Endless supplies for the decorating addict."),
("One-line-a-day 5-year memory book","Journaling","B","A tiny daily habit that becomes a treasure."),
("Reading-log + book-tracker journal","Journaling","A","For the bookworm who loves logging her reads."),
("Gratitude + affirmation card deck","Journaling","A","Daily grounding in small, kind reminders."),
("Instant photo + music combo gift","Music & Pop","C","Prints and playlists; peak teen sentimentality."),
("Vinyl record of a favourite artist","Music & Pop","C","Analog love for the fan with taste."),
("Fandom merch bundle (band/show)","Music & Pop","B","Speaks her fandom fluently; instantly beloved."),
("Aesthetic wireless earbuds","Music & Pop","C","Pretty and practical; worn every single day."),
("Beginner ukulele + songbook","Music & Pop","C","Cute, portable and genuinely learnable."),
("Karaoke mic + speaker","Music & Pop","B","Sleepover superstar energy in one gadget."),
("Concert-ticket / experience voucher","Music & Pop","D","A memory, not a thing; the gold-standard gift."),
("Custom song-lyric framed art","Music & Pop","B","Her anthem on the wall; deeply personal."),
("Enamel-pin / patch collection","Music & Pop","A","Low-cost identity pieces for bag and jacket."),
("Polaroid + concert-memory scrapbook kit","Music & Pop","B","A place to keep the nights that mattered."),
("Personalised name / initial necklace","Fashion","B","The dainty everyday piece she'll never take off."),
("Charm bracelet + starter charms","Fashion","B","A story on the wrist; add to it for years."),
("Trendy crossbody / baguette bag","Fashion","C","The 'it' bag that finishes every outfit."),
("Birthstone jewellery piece","Fashion","B","Personal, meaningful and quietly special."),
("Custom embroidered tote / denim","Fashion","B","Wearable art personalised just for her."),
("Layered-necklace / ring stack set","Fashion","B","On-trend stacking pieces for endless combos."),
("Statement sunglasses","Fashion","B","Instant confidence and a whole vibe."),
("Silk scarf (versatile styling)","Fashion","B","Hair, bag or neck; a grown-up style unlock."),
("Personalised phone case (photo/name)","Fashion","A","A daily-carry item made unmistakably hers."),
("Cosy oversized hoodie / co-ord","Fashion","C","The comfort-core piece she'll practically live in."),
("Yoga mat + starter accessories","Wellness","C","Encourages a calming, healthy movement habit."),
("Meditation / mindfulness app gift card","Wellness","B","A year of calm; wellbeing that keeps giving."),
("Self-care subscription box (3 months)","Wellness","D","Monthly delight and pampering, delivered."),
("Herbal tea sampler + infuser mug","Wellness","B","A cosy, calming daily ritual in a cup."),
("Weighted blanket (single)","Wellness","D","Anxiety-easing comfort with real, felt benefit."),
("Sunrise alarm clock (wake light)","Wellness","C","Gentler mornings for the notoriously sleepy teen."),
("Acupressure relaxation mat","Wellness","B","A surprising, effective stress-melting tool."),
("Reusable water bottle (motivational)","Wellness","B","Nudges hydration with time-marker fun."),
("Sleep-story + soundscape speaker","Wellness","C","Winds down a racing mind without a screen."),
("Desk plant + care kit","Wellness","A","A living companion that teaches gentle responsibility."),
("Pottery / paint-studio experience voucher","Experiences","C","A memorable day out with a friend or parent."),
("Baking / dessert workshop voucher","Experiences","C","Learns a skill and eats the delicious homework."),
("Photoshoot / self-portrait session","Experiences","D","Feel-good confidence and forever photos."),
("Adventure day (zip-line/kayak) voucher","Experiences","C","Adrenaline memories that beat any object."),
("Personalised star-map of a special date","Experiences","B","The night sky of a moment that mattered, framed."),
("Custom illustrated portrait (from photo)","Experiences","B","Her likeness as art; treasured and unique."),
("Movie / theme-park experience pass","Experiences","C","A guaranteed-fun day she gets to plan."),
("Dance / art class package","Experiences","C","Feeds a passion with real, ongoing lessons."),
("Personalised song / voice-note frame","Experiences","B","Play a loved one's message from a keepsake frame."),
("Memory-jar + 365-notes kit","Experiences","A","A year of little messages to open one by one."),
("Aesthetic baking starter kit","Baking & Food","B","Everything for a first Insta-worthy bake."),
("DIY chocolate-making kit","Baking & Food","B","Sweet, creative and shareable results."),
("Personalised apron + baking tools","Baking & Food","B","Cute, useful gear for the home baker."),
("Cake-decorating / piping set","Baking & Food","B","Turns simple bakes into showstoppers."),
("Bubble-tea / mocktail-making kit","Baking & Food","B","On-trend drinks she makes for friends."),
("Cookbook for teens (easy recipes)","Baking & Food","B","Builds real, confidence-boosting kitchen skills."),
("DIY dessert-jar / no-bake kit","Baking & Food","A","Pretty, easy treats with zero oven stress."),
("Ice-cream / kulfi-making kit","Baking & Food","B","Homemade frozen treats; a fun summer project."),
("Macaron / cookie baking set","Baking & Food","C","An ambitious, rewarding bake for the enthusiast."),
("Personalised recipe-journal","Baking & Food","A","A keepsake home for her favourite creations."),
("Reusable coffee cup + tote set","Sustainable & Trendy","B","On-trend eco-swaps she'll actually carry."),
("DIY upcycled-fashion kit","Sustainable & Trendy","B","Turns old clothes into new statement pieces."),
("Bamboo / eco self-care bundle","Sustainable & Trendy","B","Plastic-free swaps for the conscious teen."),
("Seed-paper / grow-your-own stationery","Sustainable & Trendy","A","Notes that literally bloom into plants."),
("Thrift-flip sewing starter kit","Sustainable & Trendy","B","Refashions finds into unique wardrobe wins."),
("Solar-powered fairy-light set","Sustainable & Trendy","B","Eco room-glow with zero electricity cost."),
("Reusable makeup-remover pad set","Sustainable & Trendy","A","A small, gift-worthy sustainable swap."),
("DIY natural-cosmetics kit","Sustainable & Trendy","B","Make clean beauty products she chooses."),
("Recycled-material trendy backpack","Sustainable & Trendy","C","Style with a conscience for daily carry."),
("Plantable herb / flower grow-kit","Sustainable & Trendy","A","A cute, rewarding intro to green living."),
]
