# -*- coding: utf-8 -*-
from data_part1 import DATA

DATA["men_36_55"] = [
("Executive leather desk organiser set","Desk & Office","C","Elevates the home office with quiet, lasting class."),
("Personalised wooden desk nameplate","Desk & Office","B","A dignified marker for the corner office or study."),
("Premium fountain pen (gift box)","Desk & Office","C","A signature tool that makes signing feel like an event."),
("Leather laptop bag / briefcase","Desk & Office","D","Handsome, durable carry for the working professional."),
("Ergonomic office chair cushion set","Desk & Office","C","Kind to the back through long working days."),
("Personalised map / city-skyline art","Desk & Office","B","A meaningful place framed for the office wall."),
("Desk humidor / cigar accessory set","Desk & Office","D","A refined indulgence for the aficionado."),
("Wireless charging desk-clock station","Desk & Office","C","Consolidates gadgets into one elegant block."),
("Premium leather journal + pen set","Desk & Office","C","For the thinker who still writes by hand."),
("Standing-desk converter","Desk & Office","D","A genuine health upgrade for the desk-bound."),
("Whisky-globe decanter + glasses set","Bar & Tasting","D","A rotating-globe decanter that owns the bar cabinet."),
("Personalised engraved whisky glasses","Bar & Tasting","C","Monogrammed crystal for the man who appreciates a dram."),
("Cigar + whisky pairing gift set","Bar & Tasting","D","An indulgent evening curated in a single box."),
("Whisky-stone chilling set (steel)","Bar & Tasting","B","Cools the pour without watering it down."),
("Home cocktail-bar tool kit","Bar & Tasting","C","Turns him into the host of the friend group."),
("Craft-gin / tasting flight set","Bar & Tasting","C","A guided journey for the curious palate."),
("Smoked-cocktail kit (wood + torch)","Bar & Tasting","C","Restaurant theatre at home; a real showpiece."),
("Wine decanter + aerator set","Bar & Tasting","C","Elevates every bottle he opens."),
("Personalised bar-caddy / coaster set","Bar & Tasting","B","A handsome, useful anchor for the home bar."),
("Beer / whisky making kit","Bar & Tasting","C","A hands-on hobby with a very drinkable payoff."),
("Percussion massage gun (pro)","Health & Wellness","C","Melts away desk-and-workout knots; feels premium."),
("Smart health / fitness watch","Health & Wellness","D","Tracks heart, sleep and stress; genuinely motivating."),
("Shiatsu neck & back massager","Health & Wellness","C","Home-spa relief for the perpetually stiff-shouldered."),
("Blood-pressure monitor (smart)","Health & Wellness","C","Thoughtful health awareness for the busy 40s."),
("Ergonomic recliner cushion / footrest","Health & Wellness","C","Everyday comfort after long, demanding days."),
("Sleep-tracking + white-noise device","Health & Wellness","C","Better rest as a gift; quietly transformative."),
("Acupressure + foot-roller set","Health & Wellness","B","Simple daily relief for aching feet and calves."),
("Posture-corrector trainer","Health & Wellness","B","A small nudge toward a healthier working spine."),
("Home air-quality monitor / purifier","Health & Wellness","D","Cleaner air for the health-conscious household."),
("Meditation / breathing coach device","Health & Wellness","C","Stress relief made tangible and habit-forming."),
("Golf accessories / rangefinder","Hobbies","D","For the weekend golfer who loves his gear."),
("Detailing kit for car enthusiasts","Hobbies","C","Turns Sunday car-care into a satisfying ritual."),
("DSLR / mirrorless lens or accessory","Hobbies","D","A meaningful upgrade for the hobby photographer."),
("Home-barista espresso machine","Hobbies","D","Cafe-quality mornings; a daily-used passion gift."),
("Premium chess / backgammon set","Hobbies","C","A handsome set for the strategist at heart."),
("Woodworking / DIY power-tool set","Hobbies","D","For the man who likes making and fixing."),
("Fishing gear / tackle upgrade","Hobbies","C","Feeds a peaceful, patient weekend passion."),
("Vinyl turntable + starter records","Hobbies","D","Analog warmth for the music-loving 40s."),
("Model-build kit (car / aircraft, detailed)","Hobbies","C","A focus-heavy, display-worthy project."),
("Astronomy telescope (quality)","Hobbies","D","Stargazing awe to share with the kids."),
("Premium wet-shave razor + stand set","Grooming & Style","C","A daily ritual upgrade that feels distinguished."),
("Automatic mechanical watch","Grooming & Style","D","A milestone timepiece to keep and pass on."),
("Signature-fragrance gift set","Grooming & Style","C","A sophisticated scent for the man of taste."),
("Full-grain leather wallet (engraved)","Grooming & Style","C","Everyday carry that ages beautifully."),
("Personalised cufflink + tie-bar set","Grooming & Style","B","Sharp detailing for the formal wardrobe."),
("Beard / grooming premium kit","Grooming & Style","C","Elevates the routine with quality tools and oils."),
("Leather weekender travel bag","Grooming & Style","D","Handsome, hard-wearing carry for getaways."),
("Sunglasses (premium polarised)","Grooming & Style","D","A face-defining accessory built to last."),
("Personalised leather belt (buckle)","Grooming & Style","B","A wardrobe staple made personal."),
("Merino / cashmere sweater","Grooming & Style","D","Effortless, timeless warmth he'll wear for years."),
("Smart-home hub + automation kit","Home & Comfort","C","Voice-controlled convenience for the whole house."),
("Premium recliner / lounge chair","Home & Comfort","D","The evening-unwind throne he'd never buy himself."),
("Robotic vacuum cleaner","Home & Comfort","D","Buys back weekend hours; universally appreciated."),
("Personalised family portrait / caricature","Home & Comfort","C","His people as art; sentimental and lasting."),
("Bluetooth vintage-radio speaker","Home & Comfort","C","Retro character with modern sound for the study."),
("Weighted / temperature-regulating blanket","Home & Comfort","D","Better sleep, gifted; surprisingly beloved."),
("Aroma diffuser + premium oils","Home & Comfort","B","A calm, good-smelling home in one gadget."),
("Personalised whisky-barrel / wall bar","Home & Comfort","D","A statement piece for the entertaining household."),
("Indoor bonsai / plant + care kit","Home & Comfort","C","A living, meditative hobby for the desk or balcony."),
("Premium coffee-table book (his passion)","Home & Comfort","C","Cars, travel, sport or art; décor with depth."),
("Masterclass / online-course annual pass","Learning","D","A year of learning from the world's best."),
("Curated non-fiction book box (his field)","Learning","C","Handpicked reads that respect his interests."),
("Language-learning premium subscription","Learning","C","Feeds a bucket-list skill for future travels."),
("Investing / finance book + tracker bundle","Learning","B","Practical tools for the wealth-building years."),
("Leadership / biography audiobook credits","Learning","C","Learning on the commute for the busy professional."),
("E-reader (glare-free)","Learning","D","Carries a library; a gift the reader will bless."),
("Photography / skill workshop voucher","Learning","C","Levels up a hobby with real, guided instruction."),
("Chess / strategy mastery course","Learning","B","Sharpens a mind that loves a challenge."),
("Documentary streaming annual gift","Learning","B","Feeds curiosity across history, science and nature."),
("Personalised leather-bound notebook set","Learning","C","A dignified home for ideas, plans and notes."),
("Luxury staycation gift box (for two)","Experiences","D","A curated escape he can share with a partner."),
("Supercar / superbike drive experience","Experiences","D","A bucket-list adrenaline day he'll never forget."),
("Golf-resort / green-fee experience","Experiences","D","A dream round for the passionate golfer."),
("Fine-dining tasting-menu voucher","Experiences","D","An evening of culinary theatre for two."),
("Personalised '#1 Dad' keepsake set","Experiences","B","Sentimental, family-first and genuinely touching."),
("Adventure weekend (trek/raft) voucher","Experiences","C","Nature and adrenaline over any object."),
("Private whisky / wine tasting session","Experiences","D","A guided, indulgent evening for the connoisseur."),
("Custom-engraved milestone crystal","Experiences","C","Marks an anniversary or achievement in style."),
("Hot-air-balloon ride for two","Experiences","D","A once-in-a-lifetime shared memory."),
("Personalised year-you-were-born print / paper","Experiences","B","Nostalgia framed; a thoughtful milestone gift."),
("Premium grill / smoker accessory set","Foodie & Gourmet","D","For the man who rules the weekend barbecue."),
("Gourmet coffee / bean-club hamper","Foodie & Gourmet","C","A curated journey for the coffee ritualist."),
("Chef-grade knife set (gift box)","Foodie & Gourmet","D","A lifetime kitchen upgrade for the home cook."),
("Whisky-and-chocolate pairing hamper","Foodie & Gourmet","D","An indulgent evening curated in one box."),
("Premium olive-oil / gourmet-pantry set","Foodie & Gourmet","C","Elevates everyday cooking with the finest staples."),
("Personalised chopping board + tools","Foodie & Gourmet","B","A handsome, functional keepsake for the cook."),
("Home pizza-oven / stone kit","Foodie & Gourmet","D","Restaurant-style pizza nights, at home."),
("Craft-beer / brewing premium kit","Foodie & Gourmet","C","A rewarding hobby with a very drinkable payoff."),
("Cheese & charcuterie premium board","Foodie & Gourmet","C","Turns an evening in into a little celebration."),
("Sous-vide precision cooker","Foodie & Gourmet","D","Precision cooking for the serious home chef."),
("Adjustable dumbbell / home-gym piece","Fitness & Outdoors","D","A full home gym in a compact upgrade."),
("Premium trekking backpack","Fitness & Outdoors","D","For the man planning his next hill escape."),
("Golf rangefinder / accessory set","Fitness & Outdoors","D","A meaningful upgrade for the weekend golfer."),
("Deep-tissue recovery massage gun","Fitness & Outdoors","C","Melts away desk-and-workout stiffness."),
("Cycling gear / accessory bundle","Fitness & Outdoors","C","Lights, tools and kit for the weekend rider."),
("Fitness smart-watch (GPS)","Fitness & Outdoors","D","Motivating health tracking for the active 40s."),
("Camping / outdoor cookware set","Fitness & Outdoors","C","Fuels the getaways he loves to plan."),
("Home rowing / compact cardio machine","Fitness & Outdoors","D","Full-body fitness without the gym commute."),
("Insulated adventure flask / bottle","Fitness & Outdoors","B","Rugged hydration for treks and long days."),
("Recovery kit (foam roller + bands)","Fitness & Outdoors","B","Keeps an active body moving and pain-free."),
]

DATA["women_36_55"] = [
("Premium at-home spa hamper","Wellness & Self-Care","D","A full pamper ritual she'd never indulge in herself."),
("Shiatsu neck & shoulder massager","Wellness & Self-Care","C","Home-spa relief for the always-carrying-everyone woman."),
("Aromatherapy diffuser + luxury oils","Wellness & Self-Care","B","Turns the home into a calm, fragrant sanctuary."),
("Weighted blanket (queen)","Wellness & Self-Care","D","Anxiety-easing, sleep-improving comfort."),
("Silk pillowcase + sleep-mask set","Wellness & Self-Care","B","Gentle-on-skin luxury felt every single night."),
("Foot-spa massager (heated)","Wellness & Self-Care","C","End-of-day relief that feels genuinely restorative."),
("Personalised robe + slipper set","Wellness & Self-Care","C","Hotel-comfort at home with her initials."),
("Acupressure mat + bolster","Wellness & Self-Care","B","A surprising, effective tension-melter."),
("Sunrise wake-light alarm","Wellness & Self-Care","C","Gentler, brighter mornings and better mood."),
("Premium skincare ritual set","Wellness & Self-Care","D","A considered upgrade to her daily self-care."),
("Personalised family-name LED sign","Home & Decor","C","A warm, custom centrepiece for the living space."),
("Luxury scented-candle collection","Home & Decor","C","Signature home scents for every mood and season."),
("Ceramic vase + premium faux florals","Home & Decor","C","Effortless, forever-fresh beauty for the shelf."),
("Personalised family portrait art","Home & Decor","C","Her people as art; treasured wall décor."),
("Handcrafted table-lamp (statement)","Home & Decor","D","A designer touch that transforms a corner."),
("Custom map / travel-memory print","Home & Decor","B","A meaningful place framed for the wall."),
("Premium bedsheet / linen gift set","Home & Decor","D","Everyday luxury she'll feel in every good night's sleep."),
("Decorative brass / metal accent set","Home & Decor","C","Elegant home accents for the design-loving eye."),
("Indoor plant + designer planter","Home & Decor","B","A living, calming touch for the home."),
("Personalised recipe / family-cookbook","Home & Decor","C","Family recipes preserved as a keepsake book."),
("Premium tea / coffee sampler hamper","Kitchen & Gourmet","C","A journey of flavours for the ritual-lover."),
("Cast-iron / premium cookware piece","Kitchen & Gourmet","D","A lifetime kitchen upgrade she'll use daily."),
("Personalised engraved cutting board","Kitchen & Gourmet","B","A beautiful, functional keepsake for the cook."),
("Gourmet chocolate / dessert box","Kitchen & Gourmet","C","An indulgent treat curated with care."),
("Air-fryer / modern kitchen gadget","Kitchen & Gourmet","D","A genuinely useful, health-friendly time-saver."),
("Artisanal olive-oil / spice gift set","Kitchen & Gourmet","C","Elevates everyday cooking with gourmet staples."),
("Stand mixer / baking upgrade","Kitchen & Gourmet","D","A dream tool for the passionate home baker."),
("Personalised apron + baking set","Kitchen & Gourmet","B","Thoughtful gear for the woman who loves to feed people."),
("Ceramic dinnerware / serveware set","Kitchen & Gourmet","D","Hosting elegance for the entertaining household."),
("Cheese / charcuterie board + tools","Kitchen & Gourmet","C","Turns evenings-in into a little celebration."),
("Personalised birthstone jewellery","Jewellery & Style","C","Meaningful, elegant and worn with love."),
("Birthstone-cluster family pendant","Jewellery & Style","C","Her whole family, worn close in one keepsake."),
("Pearl / classic jewellery set","Jewellery & Style","D","Timeless elegance for milestones and occasions."),
("Designer silk scarf / stole","Jewellery & Style","C","A versatile, luxurious style unlock."),
("Cashmere / pashmina wrap","Jewellery & Style","D","Soft, warm luxury for years of winters."),
("Personalised photo-locket","Jewellery & Style","B","A loved face kept close; sentimental and classic."),
("Premium handbag (classic cut)","Jewellery & Style","D","An everyday luxury she'll carry for years."),
("Elegant watch (leather / mesh)","Jewellery & Style","D","A refined finishing piece for every outfit."),
("Statement-earring designer set","Jewellery & Style","C","Occasion-ready sparkle curated with taste."),
("Custom-engraved bangle / kada","Jewellery & Style","C","A personal, wearable keepsake with meaning."),
("Premium gardening tool + seed set","Hobbies","C","Feeds a peaceful, rewarding balcony or garden hobby."),
("Watercolour / acrylic art master set","Hobbies","C","For the woman rediscovering her creative side."),
("Pottery-wheel / ceramics home kit","Hobbies","C","A tactile, meditative making hobby."),
("Sewing / embroidery machine (beginner)","Hobbies","D","Unlocks a whole world of making and mending."),
("Premium baking / patisserie kit","Hobbies","C","Everything for ambitious, showstopping bakes."),
("Knitting / crochet luxury yarn set","Hobbies","B","A cosy, screen-free craft with heirloom results."),
("Calligraphy / art-journaling kit","Hobbies","B","A calming creative outlet with beautiful output."),
("Candle / soap-making studio kit","Hobbies","B","Scented, giftable results; a full aesthetic hobby."),
("DSLR / camera for the hobby photographer","Hobbies","D","A meaningful tool for the creative eye."),
("Indoor herb / kitchen-garden kit","Hobbies","B","Fresh herbs on the sill; joy for the home cook."),
("Premium yoga mat + prop bundle","Fitness & Movement","C","Encourages a calming, consistent practice."),
("Smart fitness / activity watch","Fitness & Movement","D","Motivating health tracking without the fuss."),
("Massage gun (compact)","Fitness & Movement","C","Recovery and tension relief that feels luxurious."),
("Pilates ring + band home set","Fitness & Movement","B","Effective, gentle strength in minimal space."),
("Walking / hiking shoe upgrade","Fitness & Movement","C","Comfort and support for the daily-walk habit."),
("Zumba / dance-class package","Fitness & Movement","C","Joy-first fitness that never feels like a chore."),
("Foam roller + mobility kit","Fitness & Movement","B","Eases the aches of a busy, on-her-feet life."),
("Meditation-app annual gift","Fitness & Movement","B","A year of calm and better sleep."),
("Insulated water bottle (elegant)","Fitness & Movement","B","A stylish nudge toward daily hydration."),
("Under-desk / mini exercise bike","Fitness & Movement","C","Sneaks movement into the workday."),
("Masterclass / skill-course annual pass","Learning & Leisure","D","A year of learning from world-class teachers."),
("E-reader (glare-free)","Learning & Leisure","D","A whole library for the avid reader."),
("Curated book box (her genre)","Learning & Leisure","C","Handpicked reads that respect her taste."),
("Language-learning premium subscription","Learning & Leisure","C","Feeds a bucket-list skill and future travel."),
("Audiobook subscription (annual)","Learning & Leisure","C","Stories for the commute, kitchen and garden."),
("Wine / cooking appreciation course","Learning & Leisure","C","A sophisticated skill and a fun night out."),
("Documentary / streaming annual gift","Learning & Leisure","B","Feeds curiosity across the world's stories."),
("Personalised leather journal + pen","Learning & Leisure","B","A beautiful space for thoughts and plans."),
("Photography / art workshop voucher","Learning & Leisure","C","Levels up a passion with guided instruction."),
("Puzzle / brain-game premium set","Learning & Leisure","B","Relaxing, engaging downtime for a sharp mind."),
("Luxury spa-day voucher","Experiences","D","Guilt-free pampering she'd never book herself."),
("Weekend wellness-retreat gift","Experiences","D","A restorative escape from the everyday load."),
("Fine-dining tasting-menu for two","Experiences","D","An evening of culinary theatre to remember."),
("Personalised family star-map / print","Experiences","B","A meaningful night sky, framed and treasured."),
("Professional portrait / photoshoot","Experiences","D","Confidence-boosting, forever-keepsake images."),
("Pottery / art / cooking workshop","Experiences","C","A creative, memory-making day out."),
("Hot-air-balloon ride for two","Experiences","D","A once-in-a-lifetime shared memory."),
("Custom illustrated family portrait","Experiences","B","Her family or pets as art; unique and loved."),
("Milestone-year memory scrapbook (curated)","Experiences","C","A heartfelt keepsake of a life well-lived."),
("Personalised voice-note / song frame","Experiences","B","Plays a loved one's message from a keepsake."),
("Premium handbag (classic cut) reserve","Fashion & Bags","D","An everyday luxury she'll carry for years."),
("Printed designer scarf (statement)","Fashion & Bags","C","A versatile, elegant style unlock."),
("Fine-wool wrap (winter luxe)","Fashion & Bags","D","Soft, timeless warmth for every winter."),
("Elegant leather tote / work bag","Fashion & Bags","D","Refined, practical carry for the working woman."),
("Personalised travel-organiser set","Fashion & Bags","C","Sophisticated organisation for the frequent traveller."),
("Statement jewellery-piece edit","Fashion & Bags","C","Occasion-ready sparkle curated with taste."),
("Premium sunglasses (classic)","Fashion & Bags","C","A face-defining accessory built to last."),
("Personalised clutch / evening bag","Fashion & Bags","C","An elegant finishing piece for occasions."),
("Luxe loungewear / co-ord set","Fashion & Bags","C","Elevated comfort she'll reach for constantly."),
("Slim dress-watch (metal strap)","Fashion & Bags","D","A refined finishing piece for every outfit."),
("Custom family-portrait illustration","Sentimental & Personalised","B","Her family or pets as treasured art."),
("Personalised family star-map","Sentimental & Personalised","B","A meaningful night sky, framed with a date."),
("Family-name necklace (multi-initial)","Sentimental & Personalised","C","Her whole family worn close to the heart."),
("Personalised year-in-review photo-book","Sentimental & Personalised","C","A year of memories, curated and beautifully bound."),
("Engraved keepsake box","Sentimental & Personalised","B","A lovely home for letters and treasures."),
("Voice-note keepsake frame","Sentimental & Personalised","B","Plays a loved one's message on demand."),
("Custom recipe-in-her-handwriting art","Sentimental & Personalised","B","A treasured family recipe turned into wall art."),
("Personalised birthstone-family jewellery","Sentimental & Personalised","C","Her loved ones' birthstones, worn together."),
("Milestone-anniversary keepsake","Sentimental & Personalised","C","Marks a lifetime of love in keepsake form."),
("Fingerprint / handprint family art","Sentimental & Personalised","B","A literal touch of loved ones, framed."),
]
