# -*- coding: utf-8 -*-
# Gift taxonomy data. Each idea: (name, theme, price_band, why_unique)
# price_band: A=Rs 0-500, B=Rs 500-1500, C=Rs 1500-5000, D=Rs 5000+

GROUPS_META = [
    ("boys_0_12",     "Boys, 0-12",            "Curious, hands-on, growing fast"),
    ("girls_0_12",    "Girls, 0-12",           "Creative, expressive, imaginative"),
    ("teen_boys",     "Teen boys, 13-19",      "Identity, gaming, gear, hobbies"),
    ("teen_girls",    "Teen girls, 13-19",     "Aesthetic, creative, self-expression"),
    ("men_20_35",     "Men, 20-35",            "EDC, tech, fitness, first salary energy"),
    ("women_20_35",   "Women, 20-35",          "Self-care, style, home, wellness"),
    ("men_36_55",     "Men, 36-55",            "Comfort, hobbies, upgrades, legacy"),
    ("women_36_55",   "Women, 36-55",          "Wellness, home, gourmet, keepsakes"),
    ("senior_men",    "Senior men, 56+",       "Health, comfort, nostalgia, purpose"),
    ("senior_women",  "Senior women, 56+",     "Health, ease, devotion, memories"),
    ("unisex",        "Unisex / anyone",       "Couples, friends, siblings, coworkers"),
    ("premium",       "Premium, Rs 5000+",     "Statement gifts that land hard"),
]

DATA = {}

DATA["boys_0_12"] = [
("My First Science Kit with 50+ experiments","STEM & Science","B","Turns the kitchen table into a lab; screen-free curiosity for ages 6+."),
("DIY working volcano + chemistry reactions set","STEM & Science","A","The classic eruption plus safe acid-base reactions kids can repeat."),
("Glow-in-the-dark science lab kit","STEM & Science","B","Experiments that light up in the dark make the 'why' unforgettable."),
("Crystal-growing kit","STEM & Science","A","A week-long project that teaches patience and pays off with real crystals."),
("Human body 3D model build kit","STEM & Science","B","Snap organs into place to learn anatomy by doing, not memorising."),
("Solar system 3D working model","STEM & Science","B","Build the planets and see orbits move; astronomy that sticks."),
("Microscope starter kit with prepared slides","STEM & Science","C","Opens the hidden world of pond water, onion skin and insect wings."),
("Weather station build kit","STEM & Science","B","Kids track rain, wind and temperature like a real meteorologist."),
("Electric circuit 'snap' kit","STEM & Science","B","Wire a fan, buzzer and lamp with no soldering, no fear."),
("Volcano-to-dinosaur fossil dig kit","STEM & Science","A","Chisel out real fossils; part science, part treasure hunt."),
("DIY mini wooden cottage model","Building & Construction","B","A buildable keepsake that decorates the room after it's done."),
("Magnetic tile building set","Building & Construction","C","Open-ended magnetic shapes that never get 'finished' being played with."),
("Marble run construction city","Building & Construction","B","Engineering disguised as pure fun; rebuildable a hundred ways."),
("Hydraulic arm / crane build kit","Building & Construction","B","Water-powered mechanics teach force without a single battery."),
("Motorised robotic mechanical hand","Building & Construction","C","Build a gripping robot hand that actually grabs objects."),
("Wooden 3D mechanical clock kit","Building & Construction","B","A ticking, working clock they assembled themselves."),
("Nuts-and-bolts toolkit play set","Building & Construction","A","Real fine-motor practice with kid-safe drill and screws."),
("Bridge & structures engineering kit","Building & Construction","B","Test which designs hold weight; failure is the lesson."),
("Interlocking brick architecture set","Building & Construction","C","Landmark builds that reward focus and following steps."),
("Pinball machine DIY build","Building & Construction","C","They build the arcade, then play the arcade they built."),
("Screen-free coding robot for early coders","Robotics & Coding","C","Kids sequence commands with cards, learning logic before screens."),
("Line-following robot kit","Robotics & Coding","C","Build a bot that follows a track; instant, visible payoff."),
("App-controlled programmable rover","Robotics & Coding","D","Grows with the child from drag-drop blocks to real code."),
("Solar robot 14-in-1 kit","Robotics & Coding","B","One kit, fourteen sun-powered robots, zero batteries."),
("Beginner electronics 'invent' mega kit","Robotics & Coding","B","120+ projects that demystify how gadgets actually work."),
("Coding board game (unplugged)","Robotics & Coding","B","Teaches loops and conditionals around the dining table."),
("Build-your-own walking robot","Robotics & Coding","C","Motorised legs and gears turn theory into a stomping bot."),
("Micro:bit starter project pack","Robotics & Coding","C","A real programmable board for the genuinely curious kid."),
("Draw-and-drive robot (drawing bot)","Robotics & Coding","B","A wobbly robot that makes art; cause-and-effect made joyful."),
("Remote-control DIY tank build kit","Robotics & Coding","C","Assembly plus RC control; patience rewarded with a drivable machine."),
("Clay pottery wheel kit for kids","Art & Making","B","Battery-spun wheel to throw real pots; wonderfully messy."),
("3D pen for kids (low-heat)","Art & Making","C","Draw sculptures in the air; imagination becomes physical."),
("Comic-book creator kit with panels & stamps","Art & Making","A","Gives storytellers a structure to publish their own comics."),
("Spin-art machine","Art & Making","B","Every spin is a new masterpiece; process over perfection."),
("Stop-motion animation studio kit","Art & Making","C","Phone + kit = their own short films; huge creative range."),
("Sand art & terrarium bottle kit","Art & Making","A","Layered sand keepsakes that double as room décor."),
("DIY kite-making and flying kit","Art & Making","A","Craft it indoors, fly it outdoors; two hobbies in one."),
("Origami master set with paper & guide","Art & Making","A","Focus, geometry and pride in a stack of paper."),
("Scratch-art night sky posters","Art & Making","A","Reveal glowing artwork stroke by stroke; calming and screen-free."),
("Build-a-birdhouse woodcraft kit","Art & Making","B","Paint and hang it; a project that invites nature to the window."),
("Junior archery target set (safe tips)","Outdoor & Active","B","Focus and aim; a skill sport that feels grown-up."),
("Kids' metal detector","Outdoor & Active","C","Turns any park into a treasure hunt for hours."),
("Slackline starter kit for the garden","Outdoor & Active","B","Balance and confidence-building without a screen in sight."),
("Two-player water-rocket launcher","Outdoor & Active","B","Physics you can feel; soaked, delighted kids guaranteed."),
("Glow-in-the-dark flying disc","Outdoor & Active","A","Extends play into the evening; simple, social, active."),
("Bug-catching explorer kit with viewer","Outdoor & Active","A","Magnifier, net and jar for the budding naturalist."),
("Skateboard / penny board for beginners","Outdoor & Active","C","A first board is a rite of passage and a lasting hobby."),
("Pump-action foam blaster (long range)","Outdoor & Active","B","Backyard battles that get the whole street moving."),
("Kids' badminton set with net","Outdoor & Active","B","Instant garden game that parents will join in on."),
("Stomp-powered jumping rocket","Outdoor & Active","A","Jump on the pad, launch the rocket; pure kinetic joy."),
("Cooperative board game for kids","Games & Puzzles","B","Everyone wins or loses together; teaches teamwork, not tears."),
("3D wooden brain-teaser puzzle set","Games & Puzzles","A","Tactile logic puzzles that beat any tablet game."),
("Memory & strategy card game (ages 7+)","Games & Puzzles","A","Quick rounds, real thinking, endlessly replayable."),
("Themed 80-piece jigsaw (space/dino)","Games & Puzzles","A","A screen-free rainy-day ritual in a premium tin."),
("Magnetic travel chess & draughts","Games & Puzzles","B","Fits in a bag; starts a lifelong strategy habit."),
("Rubik's-style speed cube starter set","Games & Puzzles","A","A pocket puzzle that becomes a genuine skill flex."),
("Tangram + shape-logic acrylic set","Games & Puzzles","B","Spatial reasoning in beautiful, giftable form."),
("Maze marble labyrinth board","Games & Puzzles","B","Steady hands and patience in a single wooden board."),
("Escape-room-in-a-box for kids","Games & Puzzles","B","A family evening of clues, ciphers and cheering."),
("Balancing / stacking physics game","Games & Puzzles","A","Suspense and fine motor skills in a tumbling tower."),
("Astronaut projector & starry night light","Space & Nature","B","Turns the ceiling into a galaxy; calms bedtime beautifully."),
("Grow-your-own butterfly habitat","Space & Nature","C","Live caterpillars to butterflies; a lesson in life itself."),
("Ant farm / formicarium habitat","Space & Nature","B","Hypnotic real-world engineering happening behind glass."),
("Dinosaur excavation & assembly kit","Space & Nature","B","Dig, clean and build a dino skeleton like a palaeontologist."),
("Planetarium home star projector","Space & Nature","C","Accurate constellations that spark real astronomy questions."),
("Grow-a-plant science greenhouse","Space & Nature","A","Seeds to sprouts on the windowsill; responsibility made fun."),
("Glow-in-dark planets ceiling set","Space & Nature","A","A whole solar system that appears at lights-out."),
("Rock & mineral collection with guide","Space & Nature","B","A starter collection that turns walks into hunts."),
("Kids' beginner telescope","Space & Nature","C","First view of the Moon's craters is a core memory."),
("Volcano & earthquake geology kit","Space & Nature","B","Plate tectonics you can build, shake and erupt."),
("Busy board activity panel (toddler)","Early Years","B","Buckles, zips and switches build real-world fine motor skills."),
("Wooden shape-sorter & stacker","Early Years","A","The timeless first puzzle; endlessly repeatable."),
("Musical instrument starter band set","Early Years","B","Drum, xylophone and shaker for the tiny performer."),
("Water-reveal reusable painting book","Early Years","A","Paints with just water; no mess, infinite reuse."),
("Textured sensory ball pack","Early Years","A","Different grips and bumps for grabbing, rolling, giggling."),
("Soft cloth activity book (crinkle)","Early Years","A","First 'book' that survives chewing and teaches touch."),
("Nesting & stacking cups set","Early Years","A","Bath toy, tower and sorter in one humble classic."),
("Pull-along wooden animal toy","Early Years","B","Encourages those first wobbly, proud steps."),
("Peg puzzle animals / vehicles","Early Years","A","Chunky pegs for tiny fingers; names and shapes together."),
("Sound-button early words board","Early Years","B","Press to hear the word; vocabulary through play."),
("Personalised storybook with child's name","Books & Story","B","They become the hero; the most re-read book on the shelf."),
("Interactive pop-up adventure book","Books & Story","A","Paper engineering that makes reading feel like magic."),
("Audio storybook player (screen-free)","Books & Story","D","A screen-free 'Netflix for ears' for independent listening."),
("Build-your-own story dice set","Books & Story","A","Roll the dice, invent a tale; imagination on demand."),
("Illustrated first encyclopedia","Books & Story","B","Answers a thousand 'why' questions in one beautiful book."),
("Graphic-novel starter box set","Books & Story","C","Hooks reluctant readers with pictures and cliff-hangers."),
("Mythology & folktales illustrated set","Books & Story","B","Indian and world myths that fuel imagination and roots."),
("Comic subscription (3 months)","Books & Story","C","A gift that keeps arriving; anticipation every month."),
("Personalised name puzzle (wooden)","Books & Story","B","Learn to spell their own name, one peg at a time."),
("Draw-your-own-comic blank panel book","Books & Story","A","A blank stage for kids who'd rather make stories than read them."),
("Junior football / basketball hoop set","Sports & Fandom","B","Backyard sport that gets him moving and competing."),
("Personalised jersey (favourite team/name)","Sports & Fandom","B","His name on his hero's colours; instantly treasured."),
("Table-top mini football / foosball","Sports & Fandom","C","Endless indoor matches with friends and family."),
("Cricket set (bat, ball, stumps)","Sports & Fandom","B","The classic Indian backyard game in one kit."),
("Basketball / football trivia card game","Sports & Fandom","A","Feeds the young fan's obsession, screen-free."),
("Air-powered indoor hover-soccer disc","Sports & Fandom","A","Glides across the floor for safe indoor goals."),
("Sports-star collectible figure","Sports & Fandom","B","A display-worthy nod to his favourite athlete."),
("Kids' punching bag + gloves","Sports & Fandom","C","Energy release and coordination in one fun set."),
("Bowling / skittles indoor set","Sports & Fandom","B","Simple, social scoring fun for all ages."),
("Target-practice velcro dartboard","Sports & Fandom","A","Safe aiming games that build focus and giggles."),
]
