# -*- coding: utf-8 -*-
from data_part1 import DATA

DATA["senior_men"] = [
("Smart blood-pressure monitor","Health Monitoring","C","Easy daily vitals tracking; caring and genuinely useful."),
("Glucometer with easy display","Health Monitoring","B","Simple sugar monitoring for peace of mind."),
("Pulse-oximeter (fingertip)","Health Monitoring","A","Quick oxygen and pulse checks; reassuring and simple."),
("Pill organiser with alarm reminders","Health Monitoring","B","Never a missed dose; thoughtful daily support."),
("Digital thermometer (contactless)","Health Monitoring","A","Fuss-free health checks for the whole household."),
("Smartwatch with fall-detection & SOS","Health Monitoring","D","Safety and connection on the wrist; deeply thoughtful."),
("Weighing scale with health metrics","Health Monitoring","B","Simple wellness tracking he can read at a glance."),
("Digital BP + heart-rate wrist monitor","Health Monitoring","C","One-button vitals for the health-conscious senior."),
("Medical-alert bracelet (engraved)","Health Monitoring","B","Critical info kept close; safety made simple."),
("Automatic hand-sanitiser dispenser","Health Monitoring","B","Hygiene without fumbling; small daily ease."),
("Orthopaedic memory-foam pillow","Comfort & Mobility","B","Neck and spine relief for better, deeper sleep."),
("Heated foot & calf massager","Comfort & Mobility","C","Eases stiff, aching legs at the end of the day."),
("Recliner-chair cushion + footrest","Comfort & Mobility","C","Everyday comfort for the evening-newspaper chair."),
("Adjustable back-support cushion","Comfort & Mobility","B","Kind to the spine on long sitting days."),
("Warm electric heating pad","Comfort & Mobility","B","Soothing relief for joints and back on cold days."),
("Ergonomic walking cane (foldable)","Comfort & Mobility","B","Dignified, sturdy support that folds away neatly."),
("Anti-slip warm house slippers","Comfort & Mobility","A","Safe, cosy footing around the home."),
("Knee / joint support brace set","Comfort & Mobility","B","Gentle daily support for the active senior."),
("Bed-side grab rail / support handle","Comfort & Mobility","C","Safer getting up; independence preserved."),
("Neck & shoulder heat-wrap massager","Comfort & Mobility","C","Targeted relief for stubborn stiffness."),
("Premium gardening tool + kneeler set","Hobbies","C","Feeds a beloved, gentle, purposeful daily hobby."),
("Weighted wooden chess / carrom set","Hobbies","C","A handsome set for the strategist and social evenings."),
("Bird-feeder + binocular set","Hobbies","C","Invites nature to the window; calm and engaging."),
("Woodworking / whittling starter kit","Hobbies","C","A tactile, satisfying craft for patient hands."),
("Fishing gear / rod upgrade","Hobbies","C","A peaceful pastime and an excuse for fresh air."),
("Stamp / coin collecting starter album","Hobbies","B","Reignites a nostalgic, absorbing hobby."),
("Jigsaw puzzles (large-piece, scenic)","Hobbies","B","Relaxing, screen-free focus with a rewarding finish."),
("Yoga / stretching mat for seniors","Hobbies","B","Gentle movement to keep joints supple."),
("Photography (simple point-and-shoot)","Hobbies","D","Captures grandchildren and travels effortlessly."),
("Model-building / craft kit","Hobbies","C","A slow, absorbing project for steady hands."),
("E-reader with adjustable font & light","Reading & Audio","D","A whole library, easy on ageing eyes."),
("Large-print classic book collection","Reading & Audio","B","Comfortable reading of timeless favourites."),
("Audiobook subscription (annual)","Reading & Audio","C","Stories for resting eyes and quiet afternoons."),
("Bluetooth easy-speaker for music/radio","Reading & Audio","B","One-button access to his favourite songs and news."),
("Reading lamp with magnifier","Reading & Audio","B","Bright, magnified comfort for fine print."),
("Nostalgic old-Hindi-songs music player","Reading & Audio","C","Preloaded golden-era classics; instant joy."),
("Newspaper / magazine annual subscription","Reading & Audio","C","A cherished daily ritual, delivered."),
("Wireless neckband headphones (easy)","Reading & Audio","B","Comfortable listening for TV, music and calls."),
("Devotional / spiritual audio player","Reading & Audio","B","Bhajans and chants at the press of a button."),
("Personalised bookmark + book set","Reading & Audio","A","A thoughtful nudge for the lifelong reader."),
("Personalised photo-memory book (curated)","Nostalgia","C","His life story in pictures; deeply moving."),
("Retro radio Bluetooth speaker","Nostalgia","C","Old-world charm meets his favourite stations."),
("Custom family-tree framed art","Nostalgia","C","Generations mapped and honoured on the wall."),
("Digital photo frame (auto-updating)","Nostalgia","D","Family photos beamed to him from afar; connection gifted."),
("Personalised year-you-were-born print","Nostalgia","B","Nostalgia framed; headlines and facts of his birth year."),
("Vintage-film / classic-cinema collection","Nostalgia","C","The movies of his youth, ready to enjoy."),
("Custom '#1 Grandpa' keepsake","Nostalgia","B","Sentimental, warm and genuinely touching."),
("Restored old-photograph service voucher","Nostalgia","C","Brings faded family memories back to life."),
("Personalised voice-message keepsake frame","Nostalgia","B","Plays a grandchild's message on demand."),
("Memory-lane trivia / life-story journal","Nostalgia","B","Prompts him to record stories for the family."),
("Full-body massage chair pad","Wellness","D","Home-spa relaxation for tired muscles."),
("Herbal / Ayurvedic wellness hamper","Wellness","C","Thoughtful, health-first indulgence."),
("Aroma diffuser + calming oils","Wellness","B","A soothing, fragrant atmosphere at home."),
("Acupressure slippers / foot roller","Wellness","B","Simple daily circulation and relief."),
("Warm shawl / thermal blanket","Wellness","C","Cosy comfort for cold mornings and evenings."),
("Herbal tea / kadha sampler set","Wellness","B","Warm, healthful rituals in a cup."),
("Heated eye-massager for rest","Wellness","C","Relieves tired eyes; a small, felt luxury."),
("Sleep-support sound machine","Wellness","B","Gentle soundscapes for a restful night."),
("Handheld personal massager","Wellness","B","Targeted relief for shoulders, back and legs."),
("Sunlight / vitamin-D therapy lamp","Wellness","C","Mood and energy support through dull days."),
("Large-button easy mobile phone","Everyday Tech","C","Simple calls without menu confusion; independence gifted."),
("Voice-assistant smart speaker","Everyday Tech","C","Hands-free music, reminders and news; surprisingly loved."),
("Tablet with senior-friendly setup","Everyday Tech","D","Video calls with grandchildren made effortless."),
("TV soundbar for clearer dialogue","Everyday Tech","D","Makes every show easier to hear and enjoy."),
("Universal easy remote (big buttons)","Everyday Tech","B","Ends remote-juggling frustration for good."),
("Smart video-doorbell","Everyday Tech","D","See visitors safely without rushing to the door."),
("Automatic night-light (motion)","Everyday Tech","A","Safe midnight steps without fumbling for switches."),
("Key + phone finder tracker","Everyday Tech","B","Ends the daily hunt for misplaced essentials."),
("Wireless charging pad (simple)","Everyday Tech","B","Just set the phone down; no fiddly cables."),
("Emergency SOS pendant / button","Everyday Tech","C","One press for help; safety and reassurance."),
("Devotional / pilgrimage trip voucher","Experiences","D","A meaningful journey to a cherished destination."),
("Family staycation gift (accessible)","Experiences","D","Quality time together in comfort."),
("Nature / hill-station retreat voucher","Experiences","D","Fresh air and calm for a restorative break."),
("Ayurveda / wellness-centre package","Experiences","D","Rejuvenation guided by trained hands."),
("Grandchildren memory-day experience","Experiences","C","A planned outing that becomes a treasured memory."),
("Personalised legacy-interview video","Experiences","C","His life story recorded for generations."),
("Botanical-garden / heritage-tour pass","Experiences","B","A gentle, enriching day out."),
("Concert / classical-music evening tickets","Experiences","C","An evening of the music he loves, live."),
("Home chef / special-meal experience","Experiences","C","A restaurant-quality feast without leaving home."),
("Subscription for his passion (magazine/club)","Experiences","C","Ongoing joy delivered around his lifelong interest."),
("Premium pooja / prayer accessory set","Faith & Spiritual","C","Elevates a cherished daily spiritual ritual."),
("Devotional-audio easy player","Faith & Spiritual","B","Bhajans and chants at one simple press."),
("Illustrated scripture / classics (large print)","Faith & Spiritual","C","Beloved texts in a comfortable, giftable edition."),
("Rudraksha / spiritual mala","Faith & Spiritual","B","A meaningful, calming daily companion."),
("Meditation cushion + guide set","Faith & Spiritual","B","Comfort and structure for a mindful practice."),
("Personalised prayer-corner nameplate / art","Faith & Spiritual","B","A warm, custom touch for the home shrine."),
("Incense / dhoop premium collection","Faith & Spiritual","B","Fragrant essentials for daily devotion."),
("Spiritual-discourse audiobook collection","Faith & Spiritual","C","Wisdom and calm for quiet afternoons."),
("Brass / eco diya + lamp set","Faith & Spiritual","C","Elegant essentials for prayers and festivals."),
("Pilgrimage travel-comfort kit","Faith & Spiritual","C","Thoughtful gear for a meaningful journey."),
("Premium carrom board + coins","Games & Social","C","Fuels social evenings and family tournaments."),
("Weighted wooden chess set","Games & Social","C","A handsome set for the lifelong strategist."),
("Classic card-games / rummy set","Games & Social","A","The centre of many a cheerful get-together."),
("Large-piece scenic jigsaw puzzles","Games & Social","B","Relaxing, screen-free focus with a rewarding finish."),
("Ludo / snakes-and-ladders premium set","Games & Social","B","Timeless family fun across generations."),
("Crossword / Sudoku large-print book set","Games & Social","A","Daily mental exercise he'll genuinely enjoy."),
("Dominoes / backgammon wooden set","Games & Social","B","A classic, absorbing game for two."),
("Bridge / teen-patti club accessory set","Games & Social","B","Elevates his regular card evenings."),
("Memory / trivia game (senior-friendly)","Games & Social","A","Fun, sociable brain exercise for gatherings."),
("Personalised game-night board bundle","Games & Social","C","A curated set for treasured family evenings."),
]

DATA["senior_women"] = [
("Smart blood-pressure monitor","Health Monitoring","C","Easy daily vitals; caring, practical and reassuring."),
("Glucometer with large display","Health Monitoring","B","Simple sugar monitoring for daily peace of mind."),
("Pulse-oximeter (fingertip)","Health Monitoring","A","Quick oxygen and pulse checks; simple and reassuring."),
("Pill organiser with reminder alarm","Health Monitoring","B","Never a missed dose; thoughtful everyday support."),
("Smartwatch with SOS & fall-alert","Health Monitoring","D","Safety and family connection on the wrist."),
("Body-composition health scale","Health Monitoring","B","At-a-glance wellness tracking she can read easily."),
("Medical-alert bracelet (engraved)","Health Monitoring","B","Vital info kept close; safety made elegant."),
("Contactless digital thermometer","Health Monitoring","A","Fuss-free health checks for the household."),
("Posture / back-support corrector","Health Monitoring","B","Gentle support for a comfortable, upright day."),
("Automatic hand-sanitiser dispenser","Health Monitoring","B","Touch-free hygiene; small daily convenience."),
("Orthopaedic memory-foam pillow","Comfort & Ease","B","Neck and spine relief for deeper, better sleep."),
("Heated foot-spa massager","Comfort & Ease","C","End-of-day relief that feels genuinely restorative."),
("Recliner cushion + back support","Comfort & Ease","C","Everyday comfort for the favourite chair."),
("Warm electric heating pad","Comfort & Ease","B","Soothing relief for joints on cold days."),
("Anti-slip warm house slippers","Comfort & Ease","A","Safe, cosy footing around the home."),
("Lightweight foldable walking support","Comfort & Ease","B","Dignified, sturdy help that tucks away neatly."),
("Knee / joint support wraps","Comfort & Ease","B","Gentle daily support for active days."),
("Easy-grip jar & bottle opener set","Comfort & Ease","A","Restores kitchen independence; genuinely appreciated."),
("Neck & shoulder heat-massage wrap","Comfort & Ease","C","Targeted relief for stubborn stiffness."),
("Soft weighted lap blanket","Comfort & Ease","C","Cosy, calming warmth for reading and TV evenings."),
("Easy-use small chopper / mixer","Kitchen & Home","B","Takes the strain out of daily cooking prep."),
("Lightweight non-stick cookware set","Kitchen & Home","C","Easier lifting and cleaning for everyday meals."),
("Automatic tea / coffee maker (simple)","Kitchen & Home","C","Her favourite brew at the press of one button."),
("Ergonomic easy-grip kitchen tools","Kitchen & Home","B","Kind to arthritic hands; thoughtful and practical."),
("Personalised recipe / family-cookbook","Kitchen & Home","C","Her treasured recipes preserved as a keepsake."),
("Electric roti / dosa maker","Kitchen & Home","C","Effortless everyday cooking without the standing strain."),
("Insulated casserole / hot-pot set","Kitchen & Home","B","Keeps meals warm; useful for the family table."),
("Robotic vacuum / easy floor cleaner","Kitchen & Home","D","Buys back energy from daily housework."),
("Air-fryer (simple controls)","Kitchen & Home","D","Healthier, easier cooking she'll use daily."),
("Spice / masala organiser set","Kitchen & Home","B","Brings order and ease to the daily kitchen."),
("Knitting / crochet luxury yarn set","Hobbies","B","A cosy, screen-free craft with heirloom results."),
("Gardening tool + kneeler set","Hobbies","C","Feeds a beloved, gentle, purposeful hobby."),
("Embroidery / needlework kit","Hobbies","B","A patient, satisfying craft with beautiful output."),
("Large-piece scenic jigsaw puzzles","Hobbies","B","Relaxing, screen-free focus with a lovely finish."),
("Painting / colouring-for-adults set","Hobbies","B","A calming, expressive outlet for quiet afternoons."),
("Baking / dessert-making kit","Hobbies","B","Everything to spoil the family with home bakes."),
("Devotional / bhajan music player","Hobbies","B","Chants and hymns at the touch of a button."),
("Sewing machine (beginner-friendly)","Hobbies","D","Reignites a love of stitching and mending."),
("Indoor herb / flower gardening kit","Hobbies","B","A living, rewarding hobby for the balcony."),
("Sari / craft upcycling kit","Hobbies","B","Turns cherished fabrics into new creations."),
("E-reader with large adjustable font","Reading & Devotion","D","A whole library, gentle on ageing eyes."),
("Large-print books / scriptures","Reading & Devotion","B","Comfortable reading of beloved texts."),
("Audiobook / spiritual-audio subscription","Reading & Devotion","C","Stories and prayers for resting eyes."),
("Reading lamp with magnifier","Reading & Devotion","B","Bright, magnified comfort for fine print."),
("Devotional-audio easy player","Reading & Devotion","B","Aartis and bhajans at one simple press."),
("Illustrated mythology / classics set","Reading & Devotion","C","Timeless tales in a beautiful, giftable edition."),
("Personalised prayer / pooja accessory set","Reading & Devotion","C","Elevates a cherished daily ritual."),
("Wireless neckband for comfortable listening","Reading & Devotion","B","Easy audio for TV, music and calls."),
("Magazine / periodical annual subscription","Reading & Devotion","C","A cherished, regular delight delivered home."),
("Personalised bookmark + book set","Reading & Devotion","A","A thoughtful nudge for the lifelong reader."),
("Family-name / kids-initial pendant","Jewellery & Keepsakes","C","Her whole family worn close to the heart."),
("Personalised birthstone jewellery","Jewellery & Keepsakes","C","Meaningful, elegant and worn with love."),
("Pearl / traditional jewellery set","Jewellery & Keepsakes","D","Timeless elegance for festivals and occasions."),
("Custom-engraved bangle / kada","Jewellery & Keepsakes","C","A personal, wearable keepsake with meaning."),
("Photo-locket with family picture","Jewellery & Keepsakes","B","A loved face kept close; classic and sentimental."),
("Premium silk saree / stole","Jewellery & Keepsakes","D","A graceful, cherished addition to her wardrobe."),
("Personalised jewellery organiser box","Jewellery & Keepsakes","B","Keeps treasured pieces safe and beautifully stored."),
("Elegant shawl / pashmina wrap","Jewellery & Keepsakes","D","Soft, warm luxury for years of winters."),
("Custom name / mangalsutra-style piece","Jewellery & Keepsakes","D","A meaningful, personal keepsake for her."),
("Anniversary / milestone engraved locket","Jewellery & Keepsakes","C","Marks a lifetime of love in a wearable form."),
("Massage-chair pad (full body)","Wellness","D","Home-spa relaxation for tired muscles."),
("Herbal / Ayurvedic wellness hamper","Wellness","C","Thoughtful, health-first indulgence."),
("Aroma diffuser + calming oils","Wellness","B","A soothing, fragrant home atmosphere."),
("Heated eye-massager","Wellness","C","Relieves tired eyes; a small, felt luxury."),
("Acupressure foot roller / slippers","Wellness","B","Simple daily circulation and relief."),
("Herbal tea / kadha sampler","Wellness","B","Warm, healthful rituals in a cup."),
("Handheld personal massager","Wellness","B","Targeted relief for shoulders, back and legs."),
("Sleep-sound / white-noise machine","Wellness","B","Gentle soundscapes for restful nights."),
("Warm thermal / fleece blanket","Wellness","C","Cosy comfort for cold mornings and evenings."),
("Sunlight / vitamin-D therapy lamp","Wellness","C","Mood and energy support through dull days."),
("Large-button easy mobile phone","Everyday Tech & Experiences","C","Simple calls without menu confusion; independence gifted."),
("Voice-assistant smart speaker","Everyday Tech & Experiences","C","Hands-free music, reminders and bhajans; surprisingly loved."),
("Tablet set up for video calls","Everyday Tech & Experiences","D","Effortless face-to-face time with grandchildren."),
("Digital photo frame (auto-updating)","Everyday Tech & Experiences","D","Family photos beamed from afar; connection gifted."),
("Devotional / pilgrimage trip voucher","Everyday Tech & Experiences","D","A meaningful journey to a cherished place."),
("Family staycation gift (comfortable)","Everyday Tech & Experiences","D","Quality time together in comfort."),
("Personalised legacy-interview video","Everyday Tech & Experiences","C","Her life story recorded for generations."),
("Ayurveda / wellness-centre package","Everyday Tech & Experiences","D","Rejuvenation guided by trained hands."),
("Emergency SOS pendant","Everyday Tech & Experiences","C","One press for help; safety and reassurance."),
("Personalised photo-memory book (curated)","Everyday Tech & Experiences","C","Her life in pictures; deeply moving and treasured."),
("Premium pooja / prayer accessory set","Faith & Spiritual","C","Elevates a cherished daily spiritual ritual."),
("Bhajan & aarti smart audio box","Faith & Spiritual","B","Devotional favourites at one simple press."),
("Illustrated scripture / classics (large print)","Faith & Spiritual","C","Beloved texts in a comfortable, giftable edition."),
("Spiritual mala / prayer beads","Faith & Spiritual","B","A meaningful, calming daily companion."),
("Meditation cushion + guide set","Faith & Spiritual","B","Comfort and structure for a mindful practice."),
("Personalised prayer-corner art / nameplate","Faith & Spiritual","B","A warm, custom touch for the home shrine."),
("Incense / dhoop premium collection","Faith & Spiritual","B","Fragrant essentials for daily devotion."),
("Devotional-discourse audiobook set","Faith & Spiritual","C","Wisdom and calm for quiet afternoons."),
("Brass / eco diya + lamp set","Faith & Spiritual","C","Elegant essentials for prayers and festivals."),
("Pilgrimage travel-comfort kit","Faith & Spiritual","C","Thoughtful gear for a meaningful journey."),
("Soft warm shawl / stole","Comfort Clothing","C","Cosy, graceful warmth for cool mornings."),
("Anti-slip comfort footwear","Comfort Clothing","B","Safe, cushioned support for daily wear."),
("Premium cotton nightwear set","Comfort Clothing","B","Breathable, soft comfort for restful nights."),
("Thermal innerwear set (winter)","Comfort Clothing","B","Gentle, lightweight warmth under everything."),
("Easy-wear kaftan / house-dress set","Comfort Clothing","C","Elegant, effortless everyday comfort."),
("Warm bed-socks + gloves set","Comfort Clothing","A","Small cosy comforts for cold days."),
("Lightweight quilted jacket","Comfort Clothing","C","Warmth without weight for outings."),
("Personalised warm blanket-wrap","Comfort Clothing","C","A custom, cosy hug for TV and reading time."),
("Compression / support socks","Comfort Clothing","B","Gentle circulation support for tired legs."),
("Soft handloom saree / comfortable wear","Comfort Clothing","D","A graceful, cherished everyday piece."),
]
