# -*- coding: utf-8 -*-
from data_part1 import DATA

DATA["men_20_35"] = [
("Titanium / steel EDC multitool","EDC & Gadgets","C","Pocket capability that feels like a grown-up upgrade."),
("Fast-charging 3-in-1 wireless dock","EDC & Gadgets","C","Phone, watch and buds charge on one clean pad."),
("Compact 10000mAh power bank (22.5W)","EDC & Gadgets","B","Never-dead phone; the quietly essential daily hero."),
("Smart tracker tag (for keys/wallet)","EDC & Gadgets","B","Ends the frantic morning search forever."),
("Rechargeable arc lighter (windproof)","EDC & Gadgets","A","Flameless, sleek and genuinely useful gadget-cool."),
("Mini portable vacuum (car/desk)","EDC & Gadgets","A","Oddly satisfying; keeps his setup spotless."),
("Bluetooth tracker card (wallet-thin)","EDC & Gadgets","B","Slips into any wallet; peace of mind, gifted."),
("Magnetic cable-organiser set","EDC & Gadgets","A","Small fix, big daily satisfaction for a tidy desk."),
("Precision 24-in-1 screwdriver kit","EDC & Gadgets","A","For the guy who loves fixing his own gear."),
("Smart ring (fitness/sleep)","EDC & Gadgets","D","Cutting-edge health tracking without a screen."),
("Sit-stand laptop riser (portable)","Desk & WFH","C","Better posture and a healthier work-from-home day."),
("Mechanical keyboard (hot-swap)","Desk & WFH","C","The desk upgrade every remote worker secretly wants."),
("Monitor light bar (auto-dim)","Desk & WFH","C","Eases eye strain; premium desk aesthetic."),
("Under-desk cable-management tray","Desk & WFH","B","Turns a messy desk into a clean, calm workspace."),
("Personalised leather desk mat","Desk & WFH","C","His initials under a workspace he actually enjoys."),
("Noise-cancelling headphones","Desk & WFH","D","Focus armour for calls, deep work and commutes."),
("Ergonomic vertical mouse","Desk & WFH","B","Wrist relief for the guy who lives on a laptop."),
("Desk plant (low-maintenance) + pot","Desk & WFH","B","A bit of life and calm in the work corner."),
("Wireless charging desk-clock + speaker","Desk & WFH","C","Three gadgets in one tidy, useful block."),
("Focus / pomodoro timer cube","Desk & WFH","B","A tactile nudge toward deep, distraction-free work."),
("Adjustable dumbbell pair","Fitness & Outdoors","D","A full home gym compressed into two handles."),
("Massage gun (percussion)","Fitness & Outdoors","C","Post-workout recovery that feels like luxury."),
("Smart fitness watch (GPS)","Fitness & Outdoors","D","Tracks runs, sleep and rides; genuinely motivating."),
("Insulated steel gym bottle (1L)","Fitness & Outdoors","B","Keeps water cold through the toughest session."),
("Resistance-band pro set + door anchor","Fitness & Outdoors","B","Travel-friendly strength training with real range."),
("Trekking / day-hike backpack","Fitness & Outdoors","C","For the guy planning his next weekend escape."),
("Yoga / mobility mat (premium)","Fitness & Outdoors","C","Encourages recovery and flexibility, not just lifting."),
("Grip-strength & forearm trainer","Fitness & Outdoors","A","A small, addictive tool for the fitness-obsessed."),
("Cycling accessories bundle","Fitness & Outdoors","C","Lights, pump and tools for the weekend rider."),
("Foam roller (textured)","Fitness & Outdoors","B","The recovery staple that saves stiff mornings."),
("Beard-grooming premium kit","Grooming & Style","B","Oil, balm and trimmer; upgrades his whole routine."),
("Personalised leather bifold wallet","Grooming & Style","B","Engraved everyday carry that feels considered."),
("Minimalist automatic watch","Grooming & Style","D","A real grown-up timepiece; understated and lasting."),
("Signature-fragrance discovery set","Grooming & Style","C","Helps him find a scent that becomes his."),
("Premium wet-shave razor set","Grooming & Style","C","A ritual upgrade from disposable to distinguished."),
("Sunglasses (polarised, quality)","Grooming & Style","C","A face-defining accessory he'll wear constantly."),
("Personalised cufflinks / tie-bar","Grooming & Style","B","Sharp, subtle detailing for the formal wardrobe."),
("Weekender leather duffel","Grooming & Style","D","Handsome travel gear for the trip-taking twenties."),
("Minimalist card-holder + tracker","Grooming & Style","B","Slim, modern EDC for the anti-bulky-wallet guy."),
("Grooming travel dopp kit","Grooming & Style","B","Organised toiletries for the frequent flyer."),
("Whisky-stone & glass gift set","Bar & Tasting","B","Chills the pour without diluting; a classy staple."),
("Personalised engraved hip flask","Bar & Tasting","B","A pocket classic with his name or a date."),
("Cocktail-making bar tool kit","Bar & Tasting","C","Turns him into the host everyone remembers."),
("Whisky-tasting flight & journal set","Bar & Tasting","C","A guided journey for the aspiring connoisseur."),
("Ice-ball / sphere mould set","Bar & Tasting","A","Slow-melting spheres for a serious home pour."),
("Personalised whisky-glass duo","Bar & Tasting","B","Monogrammed glasses for two; great couple-adjacent gift."),
("Craft-beer brewing starter kit","Bar & Tasting","C","Brews his own; a rewarding, sharable hobby."),
("Wine-aerator + preserver set","Bar & Tasting","B","Elevates every bottle; practical and impressive."),
("Smoked-cocktail kit (wood chips)","Bar & Tasting","C","Restaurant theatre for the home bar; huge wow."),
("Coffee pour-over / aeropress kit","Bar & Tasting","C","For the guy whose mornings are a ritual."),
("Universal travel adapter (fast charge)","Travel & Experiences","B","The frequent traveller's most-used, least-glamorous hero."),
("Compression packing-cube set","Travel & Experiences","B","Doubles suitcase space; a seasoned traveller's secret."),
("Noise-isolating travel earbuds","Travel & Experiences","C","Peace on planes, trains and open offices."),
("Adventure experience voucher (rafting/paragliding)","Travel & Experiences","C","A memory over an object; adrenaline he'll retell."),
("Staycation / hotel-night gift box","Travel & Experiences","D","A curated escape for two, ready to redeem."),
("Anti-theft travel backpack","Travel & Experiences","C","Smart, secure carry for the explorer twenties."),
("Personalised leather luggage tag set","Travel & Experiences","A","Small, useful and unmistakably his on the belt."),
("Road-trip car-gadget bundle","Travel & Experiences","C","Charger, mount and tyre gauge for the driver."),
("Cooking / mixology class voucher","Travel & Experiences","C","A skill and a fun evening rolled into one."),
("Camping hammock + gear","Travel & Experiences","C","For the guy who chases weekends outdoors."),
("Beginner mirrorless camera","Hobbies","D","For the friend ready to take photography seriously."),
("Vinyl turntable (belt-drive)","Hobbies","D","Analog warmth and cover-art romance; a lasting hobby."),
("Mechanical model-build kit (car/watch)","Hobbies","C","A focus-heavy, display-worthy weekend project."),
("Home-gaming racing / flight setup piece","Hobbies","D","A serious upgrade for the sim enthusiast."),
("Astronomy telescope (intermediate)","Hobbies","D","Saturn's rings from the terrace; awe he'll share."),
("Drone with 4K camera","Hobbies","D","Aerial creativity and flying fun; big statement gift."),
("Chess set (weighted) + strategy books","Hobbies","B","Fuels a competitive, thoughtful mind."),
("Leathercraft / woodworking starter kit","Hobbies","C","A tactile, screen-free making hobby with real output."),
("Home-barista espresso setup","Hobbies","D","Cafe-quality mornings; a daily-used passion gift."),
("Guitar / instrument upgrade accessory","Hobbies","C","For the musician friend; pedals, strings, gear."),
("Levitating / floating moon lamp","Home & Lifestyle","D","A gravity-defying centrepiece and conversation-starter."),
("Smart-home starter kit (bulbs/plug)","Home & Lifestyle","C","Voice-controlled living; a genuinely fun first step."),
("Aroma diffuser + essential-oil set","Home & Lifestyle","B","Turns a bachelor pad into a calm, good-smelling space."),
("Self-stirring / temperature mug","Home & Lifestyle","B","A small daily luxury that feels futuristic."),
("Personalised map / coordinates art","Home & Lifestyle","B","A meaningful place, framed; instant wall character."),
("Bluetooth vintage gramophone speaker","Home & Lifestyle","C","Retro looks, modern sound; a décor-worthy gadget."),
("Weighted / cooling blanket (single)","Home & Lifestyle","D","Better sleep as a gift; surprisingly appreciated."),
("Custom neon quote / name sign","Home & Lifestyle","C","Personalised light that owns a wall or bar corner."),
("Indoor herb-garden kit","Home & Lifestyle","B","Fresh basil on the sill; for the guy who cooks."),
("Smart LED-strip room lighting","Home & Lifestyle","B","App-controlled ambience that transforms any room."),
("Cast-iron skillet / premium pan","Foodie & Kitchen","C","A lifetime cooking upgrade for the home chef."),
("Home cold-brew / pour-over coffee kit","Foodie & Kitchen","C","Elevates the daily coffee into a ritual."),
("Grill / BBQ tool + rub gift set","Foodie & Kitchen","C","For the guy who owns the weekend cookout."),
("Chef's knife (quality, gift box)","Foodie & Kitchen","C","The one tool a home cook truly notices."),
("Air-fryer (compact)","Foodie & Kitchen","D","Healthier, easier cooking used almost daily."),
("Gourmet hot-sauce / spice tasting set","Foodie & Kitchen","B","A flavour adventure for the culinary curious."),
("Pizza-making stone + peel kit","Foodie & Kitchen","C","Restaurant-style pizza nights at home."),
("Personalised chopping board (engraved)","Foodie & Kitchen","B","A handsome, functional keepsake for the cook."),
("Craft-cocktail syrup / bitters set","Foodie & Kitchen","B","Bar-quality drinks without leaving home."),
("Sous-vide / precision cooker","Foodie & Kitchen","D","Turns him into a genuine kitchen show-off."),
("Personalised couple / friends star-map","Sentimental & Personalised","B","A meaningful sky, framed; unexpectedly moving."),
("Custom caricature (his hobby/profession)","Sentimental & Personalised","B","A witty, personal keepsake he'll display."),
("Engraved leather journal + pen","Sentimental & Personalised","B","A dignified space for ideas, with his name."),
("Personalised photo-rolling cube","Sentimental & Personalised","C","A novel keepsake of his favourite memories."),
("Custom map of a meaningful place","Sentimental & Personalised","B","Where it began, framed for the wall."),
("Spotify-code + photo keepsake","Sentimental & Personalised","A","His anthem and a memory in one small treasure."),
("Personalised name / date bracelet","Sentimental & Personalised","B","Subtle, everyday jewellery with real meaning."),
("Engraved keepsake / watch box","Sentimental & Personalised","C","A handsome home for his treasured pieces."),
("Voice-waveform framed art","Sentimental & Personalised","B","A loved one's words turned into wall art."),
("Custom '#1' keepsake (dad/bro/friend)","Sentimental & Personalised","B","Sentimental, warm and genuinely touching."),
]

DATA["women_20_35"] = [
("At-home spa hamper (full ritual)","Self-Care & Wellness","C","A pamper evening in a box; thoughtful and indulgent."),
("Mini skincare fridge","Self-Care & Wellness","D","Chills serums and masks; a coveted, viral upgrade."),
("Jade-roller & gua-sha marble set","Self-Care & Wellness","B","A grounding daily ritual with a beautiful finish."),
("Aromatherapy diffuser + oils","Self-Care & Wellness","B","Calming ambience and wellbeing in one gift."),
("Silk pillowcase + eye-mask set","Self-Care & Wellness","B","Gentle-on-skin luxury she'll feel every night."),
("Weighted blanket (single/queen)","Self-Care & Wellness","D","Anxiety-easing comfort with real, felt benefit."),
("Acupressure mat + bolster","Self-Care & Wellness","B","A surprising, effective tension-melter after work."),
("Personalised bathrobe + slippers","Self-Care & Wellness","C","Hotel-comfort at home with her initials."),
("Sunrise wake-up light alarm","Self-Care & Wellness","C","Gentler mornings; better mood before the coffee."),
("Herbal-tea + ceramic infuser set","Self-Care & Wellness","B","A cosy, calming daily wind-down ritual."),
("Personalised name / initial necklace","Jewellery","B","The dainty everyday piece she'll live in."),
("Birthstone ring / bracelet","Jewellery","B","Personal, meaningful and quietly special."),
("Custom coordinate / map bracelet","Jewellery","B","A place that matters, worn close; deeply thoughtful."),
("Layered-necklace stacking set","Jewellery","B","On-trend combos for endless everyday styling."),
("Charm bracelet + milestone charms","Jewellery","C","A wearable story she keeps adding to."),
("Silk scarf (designer print)","Jewellery","B","Hair, neck or bag; a grown-up style unlock."),
("Personalised photo-locket","Jewellery","B","A loved face kept close; sentimental and classic."),
("Everyday hoop / stud edit set","Jewellery","B","Versatile pieces that suit work and weekend."),
("Sunglasses (trend cut, quality)","Jewellery","C","Instant confidence and a whole vibe."),
("Custom initial signet ring","Jewellery","B","Understated, timeless and unmistakably hers."),
("Personalised name LED neon sign","Home & Aesthetic","C","A statement piece for her Pinterest-worthy space."),
("Scented soy candle trio (luxury)","Home & Aesthetic","B","Mood, warmth and a signature home scent."),
("Ceramic vase + dried-flower arrangement","Home & Aesthetic","B","Zero-maintenance beauty for the shelfie corner."),
("Custom Spotify-code framed art","Home & Aesthetic","B","Her song, scannable, framed; personal décor."),
("Boho macramé wall hanging","Home & Aesthetic","B","On-trend texture that lifts any wall."),
("Galaxy / ambient projector lamp","Home & Aesthetic","B","Transforms the room's mood at the touch of a button."),
("Personalised map / star-map print","Home & Aesthetic","B","A meaningful moment turned into wall art."),
("Minimalist ceramic coffee-mug set","Home & Aesthetic","B","Everyday beauty for the morning-ritual lover."),
("Instant photo printer","Home & Aesthetic","D","Prints phone memories to pin, gift and keep."),
("Fairy-light photo-clip display","Home & Aesthetic","A","A warm, glowing wall of her favourite moments."),
("Trendy structured crossbody bag","Fashion & Bags","C","The 'it' bag that finishes every outfit."),
("Personalised tote / laptop sleeve","Fashion & Bags","B","Custom-printed carry that's practical and pretty."),
("Silk / satin co-ord loungewear set","Fashion & Bags","C","Elevated comfort she'll reach for constantly."),
("Cashmere-blend scarf / stole","Fashion & Bags","C","A soft, luxe layer for every winter."),
("Personalised phone case (name/photo)","Fashion & Bags","A","A daily-carry item made unmistakably hers."),
("Mini backpack (versatile)","Fashion & Bags","C","Hands-free style for work, travel and weekends."),
("Statement earrings edit box","Fashion & Bags","B","A curated set to switch up any look."),
("Foldable travel flats + pouch","Fashion & Bags","B","Heel-relief hero that lives in her bag."),
("Personalised passport + luggage-tag set","Fashion & Bags","B","Travel-ready and unmistakably hers."),
("Everyday minimal watch","Fashion & Bags","C","A refined finishing piece for any wrist."),
("Personalised leather journal + pen","Journaling","B","A beautiful private space with her name embossed."),
("Guided manifestation / gratitude journal","Journaling","B","Structured prompts for goals, calm and clarity."),
("One-line-a-day 5-year memory book","Journaling","B","A tiny daily habit that becomes a treasure."),
("Custom 12-month photo planner","Journaling","B","Her memories built into her daily planning."),
("Vision-board DIY kit","Journaling","B","Turns dreams visible; a real mindset tool."),
("Self-care subscription box (3 months)","Journaling","D","Monthly delight and pampering, delivered."),
("Affirmation + tarot / oracle deck","Journaling","B","Daily reflection and a moment of grounding."),
("Reading-tracker + book-lover journal","Journaling","A","For the bookworm who logs and rates her reads."),
("Habit-tracker + goal wall planner","Journaling","B","Makes intentions visible and satisfying to tick."),
("Wax-seal letter-writing set","Journaling","B","Old-world romance for the sentimental writer."),
("Candle-making studio kit","Hobbies","B","Scented, giftable results; a full aesthetic hobby."),
("Resin art & jewellery kit","Hobbies","B","Glossy, wearable pieces; creative and on-trend."),
("Watercolour / gouache art set","Hobbies","B","A calming, expressive creative outlet."),
("Pottery / clay air-dry kit","Hobbies","B","Handmade dishes and mugs; therapeutic and useful."),
("Embroidery / punch-needle kit","Hobbies","B","A slow, satisfying craft with heirloom charm."),
("Beginner baking / dessert kit","Hobbies","B","Everything for a first showstopper bake."),
("Digital drawing tablet (entry)","Hobbies","D","For the creative ready to go digital."),
("Macramé / weaving loom kit","Hobbies","B","Makes wall art and plant hangers she'll display."),
("Perfume-blending DIY kit","Hobbies","C","Craft a signature scent; unusual and delightful."),
("Indoor gardening starter set","Hobbies","B","Plant care as a soothing, rewarding habit."),
("Premium yoga mat + accessories","Fitness & Movement","C","Encourages a calming, consistent practice."),
("Pilates ring + resistance-band set","Fitness & Movement","B","Effective home workouts in minimal space."),
("Smart fitness / activity band","Fitness & Movement","C","Gamifies movement, sleep and mindful minutes."),
("Massage gun (compact)","Fitness & Movement","C","Recovery and tension relief that feels luxurious."),
("Insulated sports bottle (motivational)","Fitness & Movement","B","Nudges hydration through the day."),
("Foam roller + mobility kit","Fitness & Movement","B","Eases desk-stiff shoulders and hips."),
("Dance / Zumba class package","Fitness & Movement","C","Fun-first fitness that rarely feels like a chore."),
("Adjustable kettlebell","Fitness & Movement","C","Space-smart strength for the home workout."),
("Meditation-app annual gift card","Fitness & Movement","B","A year of calm and better sleep."),
("Cork yoga blocks + strap set","Fitness & Movement","B","Thoughtful props that deepen the practice."),
("Spa-day / massage voucher","Experiences","D","Guilt-free pampering she'd never book herself."),
("Pottery / art workshop experience","Experiences","C","A creative, memory-making day out."),
("Hot-air-balloon / adventure voucher","Experiences","D","A bucket-list memory over any object."),
("Personalised star-map of a special date","Experiences","B","The night sky of a moment that mattered, framed."),
("Professional portrait / photoshoot","Experiences","D","Confidence-boosting, forever-keepsake images."),
("Wine / cocktail tasting experience","Experiences","C","A sophisticated evening out to remember."),
("Custom illustrated couple / pet portrait","Experiences","B","Her people or pet as art; treasured and unique."),
("Weekend staycation gift box","Experiences","D","A curated escape, ready to redeem."),
("Personalised song / voice-note keepsake","Experiences","B","Plays a loved one's message from a frame."),
("Baking / mixology masterclass voucher","Experiences","C","Learns a skill and enjoys the tasty results."),
("E-reader (glare-free)","Books & Learning","D","A whole library for the avid reader."),
("Curated book box (her genre)","Books & Learning","C","Handpicked reads that respect her taste."),
("Masterclass / skill-course annual pass","Books & Learning","D","A year of learning from world-class teachers."),
("Language-learning premium subscription","Books & Learning","C","Feeds a bucket-list skill and future travel."),
("Aesthetic bookish + candle bundle","Books & Learning","B","Cosy reading-nook joy for the bookworm."),
("Personalised bookmark + tote set","Books & Learning","A","Thoughtful, useful gifts for the reader."),
("Audiobook subscription (annual)","Books & Learning","C","Stories for commutes, chores and downtime."),
("Reading-tracker journal + book-nook","Books & Learning","B","For the reader who loves logging her reads."),
("Signed / special-edition of a favourite","Books & Learning","C","A treasured collectible for the true fan."),
("Creative-writing / journaling course","Books & Learning","B","Nurtures a passion with real guidance."),
("Personalised couple / bestie star-map","Sentimental & Personalised","B","A meaningful sky, framed; unexpectedly moving."),
("Custom illustrated portrait (from photo)","Sentimental & Personalised","B","Her, her people or pet as treasured art."),
("Engraved name / initial jewellery","Sentimental & Personalised","B","A dainty everyday piece she'll live in."),
("Personalised photo-book (year in review)","Sentimental & Personalised","C","A whole year of memories, curated and bound."),
("Custom map of 'where it began'","Sentimental & Personalised","B","A meaningful place framed with a date."),
("365-notes memory jar","Sentimental & Personalised","A","A year of little messages to open daily."),
("Spotify-code + photo keepsake","Sentimental & Personalised","A","Her song and a memory in one small treasure."),
("Engraved keepsake / jewellery box","Sentimental & Personalised","B","A beautiful home for treasured trinkets."),
("Voice-note keepsake frame","Sentimental & Personalised","B","Plays a loved one's message on demand."),
("Personalised wooden photo puzzle","Sentimental & Personalised","A","A shared memory to build together and keep."),
]
